// AUTO-GENERATED by scripts/buildAllHotspots.mjs
// 6F SVG 파싱 + PNG OCR 매칭 결과
// 총 0개 셀 매칭 (디렉터리 6F: 107개)

import { FloorHotspotData } from '@/components/map/ImageOverlayMap';

const W = 4406;
const H = 3077;

const REGIONS: FloorHotspotData['regions'] = [
  {
    "building": "B",
    "polygon": [
      [
        80,
        1730
      ],
      [
        2076,
        1730
      ],
      [
        2076,
        2617
      ],
      [
        80,
        2617
      ]
    ]
  },
  {
    "building": "C",
    "polygon": [
      [
        2319,
        732
      ],
      [
        4278,
        732
      ],
      [
        4278,
        1454
      ],
      [
        2319,
        1454
      ]
    ]
  }
] as FloorHotspotData['regions'];

const STORES: FloorHotspotData['stores'] = [];

export const HOTSPOTS_6F: FloorHotspotData = {
  floor: '6F',
  imageWidth: W,
  imageHeight: H,
  regions: REGIONS,
  stores: STORES,
  facilities: [],
};
