// AUTO-GENERATED by scripts/buildAllHotspots.mjs
// 5F SVG 파싱 + PNG OCR 매칭 결과
// 총 80개 셀 매칭 (디렉터리 5F: 566개)

import { FloorHotspotData } from '@/components/map/ImageOverlayMap';

const W = 4406;
const H = 3077;

const REGIONS: FloorHotspotData['regions'] = [
  {
    "building": "A",
    "polygon": [
      [
        2083.89,
        1701
      ],
      [
        4286,
        1701
      ],
      [
        4286,
        3066
      ],
      [
        2083.89,
        3066
      ]
    ]
  },
  {
    "building": "B",
    "polygon": [
      [
        25,
        1701
      ],
      [
        2079,
        1701
      ],
      [
        2079,
        3066
      ],
      [
        25,
        3066
      ]
    ]
  },
  {
    "building": "C",
    "polygon": [
      [
        2327,
        730
      ],
      [
        4286,
        730
      ],
      [
        4286,
        1453
      ],
      [
        2327,
        1453
      ]
    ]
  },
  {
    "building": "N",
    "polygon": [
      [
        2504,
        15
      ],
      [
        3666,
        15
      ],
      [
        3666,
        593
      ],
      [
        2504,
        593
      ]
    ]
  }
] as FloorHotspotData['regions'];

const STORES = [
  {
    "code": "B-5F-106",
    "x": 118,
    "y": 2098,
    "width": 157,
    "height": 181.14
  },
  {
    "code": "B-5F-190",
    "x": 497,
    "y": 1701,
    "width": 138,
    "height": 125
  },
  {
    "code": "B-5F-107",
    "x": 278,
    "y": 2098,
    "width": 74,
    "height": 181
  },
  {
    "code": "B-5F-170",
    "x": 1986,
    "y": 1701,
    "width": 93,
    "height": 125
  },
  {
    "code": "B-5F-197",
    "x": 25,
    "y": 1701,
    "width": 97,
    "height": 125
  },
  {
    "code": "A-5F-106",
    "x": 4138,
    "y": 2539,
    "width": 148,
    "height": 70
  },
  {
    "code": "B-5F-194",
    "x": 278,
    "y": 1701,
    "width": 75,
    "height": 125
  },
  {
    "code": "B-5F-195",
    "x": 201,
    "y": 1701,
    "width": 75,
    "height": 125
  },
  {
    "code": "B-5F-196",
    "x": 124,
    "y": 1701,
    "width": 75,
    "height": 125
  },
  {
    "code": "B-5F-182",
    "x": 1134,
    "y": 1701,
    "width": 71,
    "height": 125
  },
  {
    "code": "B-5F-188",
    "x": 708,
    "y": 1701,
    "width": 71,
    "height": 125
  },
  {
    "code": "A-5F-209",
    "x": 3982,
    "y": 1701,
    "width": 70,
    "height": 125
  },
  {
    "code": "A-5F-210",
    "x": 3911,
    "y": 1701,
    "width": 69,
    "height": 125
  },
  {
    "code": "A-5F-214",
    "x": 3627,
    "y": 1701,
    "width": 69,
    "height": 125
  },
  {
    "code": "B-5F-185",
    "x": 923,
    "y": 1701,
    "width": 69,
    "height": 125
  },
  {
    "code": "B-5F-186",
    "x": 852,
    "y": 1701,
    "width": 69,
    "height": 125
  },
  {
    "code": "B-5F-187",
    "x": 781,
    "y": 1701,
    "width": 69,
    "height": 125
  },
  {
    "code": "B-5F-189",
    "x": 637,
    "y": 1701,
    "width": 69,
    "height": 125
  },
  {
    "code": "B-5F-192",
    "x": 426,
    "y": 1701,
    "width": 69,
    "height": 125
  },
  {
    "code": "A-5F-207",
    "x": 4138,
    "y": 1701,
    "width": 148,
    "height": 62
  },
  {
    "code": "B-5F-181",
    "x": 1207,
    "y": 1701,
    "width": 67,
    "height": 125
  },
  {
    "code": "B-5F-145",
    "x": 191,
    "y": 1963,
    "width": 97,
    "height": 76
  },
  {
    "code": "A-5F-183",
    "x": 2085,
    "y": 1971,
    "width": 116,
    "height": 63
  },
  {
    "code": "B-5F-146",
    "x": 83,
    "y": 1962,
    "width": 105,
    "height": 77
  },
  {
    "code": "A-5F-216",
    "x": 2204,
    "y": 2742,
    "width": 117,
    "height": 62
  },
  {
    "code": "A-5F-204",
    "x": 4211,
    "y": 1885,
    "width": 75,
    "height": 86
  },
  {
    "code": "B-5F-112",
    "x": 1996,
    "y": 1963,
    "width": 82,
    "height": 76
  },
  {
    "code": "B-5F-116",
    "x": 1996,
    "y": 1885,
    "width": 82,
    "height": 75
  },
  {
    "code": "B-5F-108",
    "x": 354,
    "y": 2098,
    "width": 79,
    "height": 76
  },
  {
    "code": "B-5F-102",
    "x": 703,
    "y": 2175,
    "width": 76,
    "height": 77
  },
  {
    "code": "B-5F-103",
    "x": 568,
    "y": 2175,
    "width": 76,
    "height": 77
  },
  {
    "code": "B-5F-140",
    "x": 703,
    "y": 1962,
    "width": 76,
    "height": 77
  },
  {
    "code": "B-5F-141",
    "x": 568,
    "y": 1962,
    "width": 76,
    "height": 77
  },
  {
    "code": "B-5F-211",
    "x": 1555,
    "y": 2737,
    "width": 76,
    "height": 76
  },
  {
    "code": "A-5F-169",
    "x": 3627,
    "y": 1963,
    "width": 76,
    "height": 76
  },
  {
    "code": "A-5F-198",
    "x": 3627,
    "y": 1885,
    "width": 76,
    "height": 76
  },
  {
    "code": "B-5F-111",
    "x": 703,
    "y": 2098,
    "width": 76,
    "height": 75
  },
  {
    "code": "B-5F-110",
    "x": 568,
    "y": 2098,
    "width": 76,
    "height": 75
  },
  {
    "code": "B-5F-150",
    "x": 348,
    "y": 1885,
    "width": 75,
    "height": 75
  },
  {
    "code": "B-5F-100",
    "x": 851,
    "y": 2174,
    "width": 71,
    "height": 78
  },
  {
    "code": "B-5F-147",
    "x": 62,
    "y": 1885,
    "width": 83,
    "height": 75
  },
  {
    "code": "B-5F-136",
    "x": 1063,
    "y": 1962,
    "width": 71,
    "height": 77
  },
  {
    "code": "B-5F-137",
    "x": 923,
    "y": 1962,
    "width": 70,
    "height": 77
  },
  {
    "code": "B-5F-138",
    "x": 851,
    "y": 1962,
    "width": 70,
    "height": 77
  },
  {
    "code": "B-5F-113",
    "x": 851,
    "y": 2098,
    "width": 71,
    "height": 75
  },
  {
    "code": "A-5F-108",
    "x": 3911,
    "y": 2389,
    "width": 70,
    "height": 76
  },
  {
    "code": "A-5F-125",
    "x": 3911,
    "y": 2311,
    "width": 70,
    "height": 76
  },
  {
    "code": "A-5F-128",
    "x": 3982,
    "y": 2176,
    "width": 70,
    "height": 76
  },
  {
    "code": "A-5F-160",
    "x": 3982,
    "y": 2098,
    "width": 70,
    "height": 76
  },
  {
    "code": "A-5F-165",
    "x": 3982,
    "y": 1963,
    "width": 70,
    "height": 76
  },
  {
    "code": "A-5F-202",
    "x": 3982,
    "y": 1885,
    "width": 70,
    "height": 76
  },
  {
    "code": "B-5F-132",
    "x": 1349,
    "y": 1962,
    "width": 69,
    "height": 77
  },
  {
    "code": "B-5F-133",
    "x": 1278,
    "y": 1962,
    "width": 69,
    "height": 77
  },
  {
    "code": "B-5F-134",
    "x": 1207,
    "y": 1962,
    "width": 69,
    "height": 77
  },
  {
    "code": "B-5F-135",
    "x": 1136,
    "y": 1962,
    "width": 69,
    "height": 77
  },
  {
    "code": "B-5F-142",
    "x": 497,
    "y": 1962,
    "width": 69,
    "height": 77
  },
  {
    "code": "B-5F-114",
    "x": 1135,
    "y": 2098,
    "width": 70,
    "height": 75
  },
  {
    "code": "B-5F-109",
    "x": 496,
    "y": 2098,
    "width": 70,
    "height": 75
  },
  {
    "code": "B-5F-158",
    "x": 1064,
    "y": 1885,
    "width": 70,
    "height": 75
  },
  {
    "code": "B-5F-157",
    "x": 923,
    "y": 1885,
    "width": 70,
    "height": 75
  },
  {
    "code": "B-5F-156",
    "x": 851,
    "y": 1885,
    "width": 70,
    "height": 75
  },
  {
    "code": "A-5F-103",
    "x": 3911,
    "y": 2524,
    "width": 69,
    "height": 76
  },
  {
    "code": "A-5F-129",
    "x": 3911,
    "y": 2176,
    "width": 69,
    "height": 76
  },
  {
    "code": "A-5F-189",
    "x": 3911,
    "y": 2098,
    "width": 69,
    "height": 76
  },
  {
    "code": "A-5F-166",
    "x": 3911,
    "y": 1963,
    "width": 69,
    "height": 76
  },
  {
    "code": "A-5F-167",
    "x": 3840,
    "y": 1963,
    "width": 69,
    "height": 76
  },
  {
    "code": "A-5F-201",
    "x": 3911,
    "y": 1885,
    "width": 69,
    "height": 76
  },
  {
    "code": "A-5F-200",
    "x": 3840,
    "y": 1885,
    "width": 69,
    "height": 76
  },
  {
    "code": "B-5F-101",
    "x": 781,
    "y": 2175,
    "width": 68,
    "height": 77
  },
  {
    "code": "B-5F-139",
    "x": 781,
    "y": 1962,
    "width": 68,
    "height": 77
  },
  {
    "code": "B-5F-117",
    "x": 1349,
    "y": 2098,
    "width": 69,
    "height": 75
  },
  {
    "code": "B-5F-115",
    "x": 1207,
    "y": 2098,
    "width": 69,
    "height": 75
  },
  {
    "code": "B-5F-162",
    "x": 1349,
    "y": 1885,
    "width": 69,
    "height": 75
  },
  {
    "code": "B-5F-161",
    "x": 1278,
    "y": 1885,
    "width": 69,
    "height": 75
  },
  {
    "code": "B-5F-160",
    "x": 1207,
    "y": 1885,
    "width": 69,
    "height": 75
  },
  {
    "code": "B-5F-152",
    "x": 497,
    "y": 1885,
    "width": 69,
    "height": 75
  },
  {
    "code": "B-5F-151",
    "x": 426,
    "y": 1885,
    "width": 69,
    "height": 75
  },
  {
    "code": "B-5F-148",
    "x": 147,
    "y": 1885,
    "width": 69,
    "height": 75
  },
  {
    "code": "B-5F-155",
    "x": 781,
    "y": 1885,
    "width": 68,
    "height": 75
  },
  {
    "code": "A-5F-206",
    "x": 4211,
    "y": 1765,
    "width": 75,
    "height": 61
  }
];

export const HOTSPOTS_5F: FloorHotspotData = {
  floor: '5F',
  imageWidth: W,
  imageHeight: H,
  regions: REGIONS,
  stores: STORES,
  facilities: [],
};
