// AUTO-GENERATED by scripts/buildAllHotspots.mjs
// 4F SVG 파싱 + PNG OCR 매칭 결과
// 총 1개 셀 매칭 (디렉터리 4F: 58개)

import { FloorHotspotData } from '@/components/map/ImageOverlayMap';

const W = 4406;
const H = 3077;

const REGIONS: FloorHotspotData['regions'] = [
  {
    "building": "B",
    "polygon": [
      [
        538,
        1725
      ],
      [
        2062,
        1725
      ],
      [
        2062,
        3056
      ],
      [
        538,
        3056
      ]
    ]
  },
  {
    "building": "N",
    "polygon": [
      [
        2464,
        17
      ],
      [
        3626,
        17
      ],
      [
        3626,
        600
      ],
      [
        2464,
        600
      ]
    ]
  }
] as FloorHotspotData['regions'];

const STORES = [
  {
    "code": "B-4F-062",
    "x": 613,
    "y": 2815,
    "width": 70,
    "height": 84
  }
];

export const HOTSPOTS_4F: FloorHotspotData = {
  floor: '4F',
  imageWidth: W,
  imageHeight: H,
  regions: REGIONS,
  stores: STORES,
  facilities: [],
};
