// AUTO-GENERATED by scripts/buildAllHotspots.mjs
// 3F SVG 파싱 + PNG OCR 매칭 결과
// 총 173개 셀 매칭 (디렉터리 3F: 703개)

import { FloorHotspotData } from '@/components/map/ImageOverlayMap';

const W = 4406;
const H = 3077;

const REGIONS: FloorHotspotData['regions'] = [
  {
    "building": "A",
    "polygon": [
      [
        2071,
        1705
      ],
      [
        4294,
        1705
      ],
      [
        4294,
        3070
      ],
      [
        2071,
        3070
      ]
    ]
  },
  {
    "building": "B",
    "polygon": [
      [
        20,
        1610
      ],
      [
        2086,
        1610
      ],
      [
        2086,
        3070
      ],
      [
        20,
        3070
      ]
    ]
  },
  {
    "building": "C",
    "polygon": [
      [
        2073,
        734
      ],
      [
        4294,
        734
      ],
      [
        4294,
        1700
      ],
      [
        2073,
        1700
      ]
    ]
  },
  {
    "building": "N",
    "polygon": [
      [
        2481,
        14
      ],
      [
        3642,
        14
      ],
      [
        3642,
        595
      ],
      [
        2481,
        595
      ]
    ]
  }
] as FloorHotspotData['regions'];

const STORES = [
  {
    "code": "B-3F-3125",
    "x": 1001,
    "y": 1705,
    "width": 97,
    "height": 125
  },
  {
    "code": "B-3F-3187",
    "x": 1925,
    "y": 2243,
    "width": 161,
    "height": 67
  },
  {
    "code": "A-3F-3101",
    "x": 2334,
    "y": 2539,
    "width": 161,
    "height": 65
  },
  {
    "code": "B-3F-3204",
    "x": 1925,
    "y": 2475,
    "width": 161,
    "height": 63
  },
  {
    "code": "A-3F-3122",
    "x": 2335,
    "y": 2180,
    "width": 159,
    "height": 64
  },
  {
    "code": "B-3F-3205",
    "x": 1925,
    "y": 2541,
    "width": 161,
    "height": 63
  },
  {
    "code": "A-3F-3102",
    "x": 2335,
    "y": 2475,
    "width": 159,
    "height": 62
  },
  {
    "code": "A-3F-3121",
    "x": 2335,
    "y": 2247,
    "width": 159,
    "height": 62
  },
  {
    "code": "B-3F-3241",
    "x": 948,
    "y": 3018,
    "width": 190,
    "height": 51
  },
  {
    "code": "B-3F-3186",
    "x": 1925,
    "y": 2180,
    "width": 161,
    "height": 61
  },
  {
    "code": "C-3F-3291",
    "x": 3433,
    "y": 1197,
    "width": 100,
    "height": 82
  },
  {
    "code": "C-3F-3310",
    "x": 3433,
    "y": 1113,
    "width": 100,
    "height": 82
  },
  {
    "code": "C-3F-3359",
    "x": 2783,
    "y": 735,
    "width": 74,
    "height": 109
  },
  {
    "code": "C-3F-3292",
    "x": 3535,
    "y": 1197,
    "width": 98,
    "height": 82
  },
  {
    "code": "C-3F-3309",
    "x": 3535,
    "y": 1113,
    "width": 98,
    "height": 82
  },
  {
    "code": "C-3F-3339",
    "x": 4215,
    "y": 868,
    "width": 79,
    "height": 99
  },
  {
    "code": "C-3F-3272",
    "x": 3137,
    "y": 1368,
    "width": 86,
    "height": 89
  },
  {
    "code": "C-3F-3334",
    "x": 3990,
    "y": 968,
    "width": 83,
    "height": 92
  },
  {
    "code": "C-3F-3328",
    "x": 3434,
    "y": 984,
    "width": 99,
    "height": 76
  },
  {
    "code": "C-3F-3247",
    "x": 3138,
    "y": 1463,
    "width": 85,
    "height": 88
  },
  {
    "code": "C-3F-3329",
    "x": 3535,
    "y": 984,
    "width": 98,
    "height": 76
  },
  {
    "code": "C-3F-3358",
    "x": 2712,
    "y": 735,
    "width": 68,
    "height": 109
  },
  {
    "code": "C-3F-3357",
    "x": 2641,
    "y": 735,
    "width": 68,
    "height": 109
  },
  {
    "code": "C-3F-3356",
    "x": 2570,
    "y": 735,
    "width": 68,
    "height": 109
  },
  {
    "code": "C-3F-3263",
    "x": 3990,
    "y": 1368,
    "width": 82,
    "height": 89
  },
  {
    "code": "C-3F-3336",
    "x": 4215,
    "y": 969,
    "width": 79,
    "height": 91
  },
  {
    "code": "C-3F-3252",
    "x": 3635,
    "y": 1462,
    "width": 79,
    "height": 90
  },
  {
    "code": "A-3F-3216",
    "x": 4215,
    "y": 1705,
    "width": 79,
    "height": 89
  },
  {
    "code": "A-3F-3209",
    "x": 3635,
    "y": 1705,
    "width": 79,
    "height": 89
  },
  {
    "code": "A-3F-3204",
    "x": 3137,
    "y": 1705,
    "width": 79,
    "height": 89
  },
  {
    "code": "C-3F-3267",
    "x": 3635,
    "y": 1368,
    "width": 79,
    "height": 89
  },
  {
    "code": "B-3F-3194",
    "x": 1001,
    "y": 2500,
    "width": 67,
    "height": 104
  },
  {
    "code": "A-3F-3214",
    "x": 3990,
    "y": 1705,
    "width": 78,
    "height": 89
  },
  {
    "code": "C-3F-3297",
    "x": 3990,
    "y": 1197,
    "width": 84,
    "height": 82
  },
  {
    "code": "C-3F-3304",
    "x": 3990,
    "y": 1113,
    "width": 84,
    "height": 82
  },
  {
    "code": "C-3F-3221",
    "x": 3990,
    "y": 1611,
    "width": 78,
    "height": 88
  },
  {
    "code": "C-3F-3230",
    "x": 3138,
    "y": 1611,
    "width": 78,
    "height": 88
  },
  {
    "code": "A-3F-3185",
    "x": 3137,
    "y": 1871,
    "width": 82,
    "height": 83
  },
  {
    "code": "C-3F-3276",
    "x": 2782,
    "y": 1368,
    "width": 75,
    "height": 89
  },
  {
    "code": "B-3F-3193",
    "x": 1384,
    "y": 2393,
    "width": 91,
    "height": 73
  },
  {
    "code": "B-3F-3188",
    "x": 1384,
    "y": 2318,
    "width": 91,
    "height": 73
  },
  {
    "code": "A-3F-3164",
    "x": 3137,
    "y": 1956,
    "width": 82,
    "height": 81
  },
  {
    "code": "A-3F-3177",
    "x": 3990,
    "y": 1871,
    "width": 81,
    "height": 82
  },
  {
    "code": "A-3F-3199",
    "x": 2783,
    "y": 1705,
    "width": 74,
    "height": 89
  },
  {
    "code": "B-3F-3192",
    "x": 1292,
    "y": 2393,
    "width": 90,
    "height": 73
  },
  {
    "code": "A-3F-3172",
    "x": 3990,
    "y": 1956,
    "width": 81,
    "height": 81
  },
  {
    "code": "A-3F-3181",
    "x": 3635,
    "y": 1871,
    "width": 79,
    "height": 83
  },
  {
    "code": "C-3F-3234",
    "x": 2783,
    "y": 1611,
    "width": 74,
    "height": 88
  },
  {
    "code": "C-3F-3243",
    "x": 2783,
    "y": 1463,
    "width": 74,
    "height": 88
  },
  {
    "code": "C-3F-3293",
    "x": 3635,
    "y": 1197,
    "width": 79,
    "height": 82
  },
  {
    "code": "C-3F-3308",
    "x": 3635,
    "y": 1113,
    "width": 79,
    "height": 82
  },
  {
    "code": "B-3F-3191",
    "x": 1203,
    "y": 2393,
    "width": 88,
    "height": 73
  },
  {
    "code": "B-3F-3190",
    "x": 1203,
    "y": 2318,
    "width": 88,
    "height": 73
  },
  {
    "code": "A-3F-3168",
    "x": 3635,
    "y": 1956,
    "width": 79,
    "height": 81
  },
  {
    "code": "C-3F-3333",
    "x": 3919,
    "y": 968,
    "width": 69,
    "height": 92
  },
  {
    "code": "C-3F-3332",
    "x": 3848,
    "y": 968,
    "width": 69,
    "height": 92
  },
  {
    "code": "A-3F-3103",
    "x": 3041,
    "y": 2392,
    "width": 89,
    "height": 71
  },
  {
    "code": "C-3F-3273",
    "x": 3066,
    "y": 1368,
    "width": 70,
    "height": 89
  },
  {
    "code": "C-3F-3274",
    "x": 2995,
    "y": 1368,
    "width": 70,
    "height": 89
  },
  {
    "code": "C-3F-3277",
    "x": 2711,
    "y": 1368,
    "width": 70,
    "height": 89
  },
  {
    "code": "C-3F-3222",
    "x": 3919,
    "y": 1610,
    "width": 69,
    "height": 90
  },
  {
    "code": "C-3F-3223",
    "x": 3848,
    "y": 1610,
    "width": 69,
    "height": 90
  },
  {
    "code": "C-3F-3227",
    "x": 3493,
    "y": 1610,
    "width": 69,
    "height": 90
  },
  {
    "code": "C-3F-3228",
    "x": 3422,
    "y": 1610,
    "width": 69,
    "height": 90
  },
  {
    "code": "C-3F-3254",
    "x": 3848,
    "y": 1462,
    "width": 69,
    "height": 90
  },
  {
    "code": "C-3F-3251",
    "x": 3564,
    "y": 1462,
    "width": 69,
    "height": 90
  },
  {
    "code": "C-3F-3250",
    "x": 3493,
    "y": 1462,
    "width": 69,
    "height": 90
  },
  {
    "code": "C-3F-3249",
    "x": 3422,
    "y": 1462,
    "width": 69,
    "height": 90
  },
  {
    "code": "A-3F-3136",
    "x": 3990,
    "y": 2180,
    "width": 81,
    "height": 76
  },
  {
    "code": "A-3F-3139",
    "x": 3990,
    "y": 2102,
    "width": 81,
    "height": 76
  },
  {
    "code": "A-3F-3160",
    "x": 2782,
    "y": 1956,
    "width": 76,
    "height": 81
  },
  {
    "code": "C-3F-3315",
    "x": 2782,
    "y": 1113,
    "width": 75,
    "height": 82
  },
  {
    "code": "A-3F-3213",
    "x": 3919,
    "y": 1705,
    "width": 69,
    "height": 89
  },
  {
    "code": "A-3F-3212",
    "x": 3848,
    "y": 1705,
    "width": 69,
    "height": 89
  },
  {
    "code": "A-3F-3208",
    "x": 3564,
    "y": 1705,
    "width": 69,
    "height": 89
  },
  {
    "code": "A-3F-3207",
    "x": 3493,
    "y": 1705,
    "width": 69,
    "height": 89
  },
  {
    "code": "A-3F-3206",
    "x": 3422,
    "y": 1705,
    "width": 69,
    "height": 89
  },
  {
    "code": "C-3F-3265",
    "x": 3848,
    "y": 1368,
    "width": 69,
    "height": 89
  },
  {
    "code": "C-3F-3268",
    "x": 3564,
    "y": 1368,
    "width": 69,
    "height": 89
  },
  {
    "code": "C-3F-3269",
    "x": 3493,
    "y": 1368,
    "width": 69,
    "height": 89
  },
  {
    "code": "C-3F-3270",
    "x": 3422,
    "y": 1368,
    "width": 69,
    "height": 89
  },
  {
    "code": "A-3F-3120",
    "x": 3042,
    "y": 2321,
    "width": 88,
    "height": 69
  },
  {
    "code": "A-3F-3189",
    "x": 2783,
    "y": 1871,
    "width": 74,
    "height": 82
  },
  {
    "code": "C-3F-3285",
    "x": 2783,
    "y": 1197,
    "width": 74,
    "height": 82
  },
  {
    "code": "A-3F-3203",
    "x": 3067,
    "y": 1705,
    "width": 68,
    "height": 89
  },
  {
    "code": "A-3F-3202",
    "x": 2996,
    "y": 1705,
    "width": 68,
    "height": 89
  },
  {
    "code": "A-3F-3198",
    "x": 2712,
    "y": 1705,
    "width": 68,
    "height": 89
  },
  {
    "code": "A-3F-3132",
    "x": 3635,
    "y": 2180,
    "width": 79,
    "height": 76
  },
  {
    "code": "A-3F-3129",
    "x": 3137,
    "y": 2180,
    "width": 79,
    "height": 76
  },
  {
    "code": "A-3F-3143",
    "x": 3635,
    "y": 2102,
    "width": 79,
    "height": 76
  },
  {
    "code": "C-3F-3330",
    "x": 3635,
    "y": 984,
    "width": 79,
    "height": 76
  },
  {
    "code": "B-3F-3120",
    "x": 905,
    "y": 2105,
    "width": 95,
    "height": 63
  },
  {
    "code": "C-3F-3226",
    "x": 3564,
    "y": 1611,
    "width": 68,
    "height": 88
  },
  {
    "code": "C-3F-3231",
    "x": 3067,
    "y": 1611,
    "width": 68,
    "height": 88
  },
  {
    "code": "C-3F-3232",
    "x": 2996,
    "y": 1611,
    "width": 68,
    "height": 88
  },
  {
    "code": "C-3F-3235",
    "x": 2712,
    "y": 1611,
    "width": 68,
    "height": 88
  },
  {
    "code": "C-3F-3246",
    "x": 3067,
    "y": 1463,
    "width": 68,
    "height": 88
  },
  {
    "code": "C-3F-3245",
    "x": 2996,
    "y": 1463,
    "width": 68,
    "height": 88
  },
  {
    "code": "C-3F-3242",
    "x": 2712,
    "y": 1463,
    "width": 68,
    "height": 88
  },
  {
    "code": "C-3F-3241",
    "x": 2641,
    "y": 1463,
    "width": 68,
    "height": 88
  },
  {
    "code": "A-3F-3104",
    "x": 3132,
    "y": 2392,
    "width": 83,
    "height": 71
  },
  {
    "code": "B-3F-3116",
    "x": 905,
    "y": 2358,
    "width": 95,
    "height": 62
  },
  {
    "code": "A-3F-3147",
    "x": 3138,
    "y": 2102,
    "width": 78,
    "height": 75
  },
  {
    "code": "B-3F-3112",
    "x": 905,
    "y": 2616,
    "width": 94,
    "height": 62
  },
  {
    "code": "B-3F-3117",
    "x": 905,
    "y": 2295,
    "width": 95,
    "height": 61
  },
  {
    "code": "B-3F-3118",
    "x": 905,
    "y": 2232,
    "width": 95,
    "height": 61
  },
  {
    "code": "C-3F-3312",
    "x": 3066,
    "y": 1113,
    "width": 70,
    "height": 82
  },
  {
    "code": "C-3F-3313",
    "x": 2995,
    "y": 1113,
    "width": 70,
    "height": 82
  },
  {
    "code": "C-3F-3316",
    "x": 2711,
    "y": 1113,
    "width": 70,
    "height": 82
  },
  {
    "code": "C-3F-3317",
    "x": 2640,
    "y": 1113,
    "width": 70,
    "height": 82
  },
  {
    "code": "A-3F-3119",
    "x": 3132,
    "y": 2321,
    "width": 83,
    "height": 69
  },
  {
    "code": "A-3F-3178",
    "x": 3919,
    "y": 1871,
    "width": 69,
    "height": 83
  },
  {
    "code": "A-3F-3179",
    "x": 3848,
    "y": 1871,
    "width": 69,
    "height": 83
  },
  {
    "code": "A-3F-3182",
    "x": 3564,
    "y": 1871,
    "width": 69,
    "height": 83
  },
  {
    "code": "B-3F-3119",
    "x": 905,
    "y": 2170,
    "width": 95,
    "height": 60
  },
  {
    "code": "A-3F-3151",
    "x": 2782,
    "y": 2102,
    "width": 75,
    "height": 76
  },
  {
    "code": "A-3F-3163",
    "x": 3066,
    "y": 1956,
    "width": 70,
    "height": 81
  },
  {
    "code": "A-3F-3162",
    "x": 2995,
    "y": 1956,
    "width": 70,
    "height": 81
  },
  {
    "code": "A-3F-3159",
    "x": 2711,
    "y": 1956,
    "width": 70,
    "height": 81
  },
  {
    "code": "C-3F-3296",
    "x": 3919,
    "y": 1197,
    "width": 69,
    "height": 82
  },
  {
    "code": "C-3F-3295",
    "x": 3848,
    "y": 1197,
    "width": 69,
    "height": 82
  },
  {
    "code": "C-3F-3305",
    "x": 3919,
    "y": 1113,
    "width": 69,
    "height": 82
  },
  {
    "code": "C-3F-3306",
    "x": 3848,
    "y": 1113,
    "width": 69,
    "height": 82
  },
  {
    "code": "C-3F-3324",
    "x": 2783,
    "y": 984,
    "width": 74,
    "height": 76
  },
  {
    "code": "C-3F-3349",
    "x": 2783,
    "y": 906,
    "width": 74,
    "height": 76
  },
  {
    "code": "A-3F-3171",
    "x": 3919,
    "y": 1956,
    "width": 69,
    "height": 81
  },
  {
    "code": "A-3F-3170",
    "x": 3848,
    "y": 1956,
    "width": 69,
    "height": 81
  },
  {
    "code": "A-3F-3167",
    "x": 3564,
    "y": 1956,
    "width": 69,
    "height": 81
  },
  {
    "code": "A-3F-3186",
    "x": 3067,
    "y": 1871,
    "width": 68,
    "height": 82
  },
  {
    "code": "A-3F-3187",
    "x": 2996,
    "y": 1871,
    "width": 68,
    "height": 82
  },
  {
    "code": "A-3F-3190",
    "x": 2712,
    "y": 1871,
    "width": 68,
    "height": 82
  },
  {
    "code": "A-3F-3191",
    "x": 2641,
    "y": 1871,
    "width": 68,
    "height": 82
  },
  {
    "code": "C-3F-3288",
    "x": 3067,
    "y": 1197,
    "width": 68,
    "height": 82
  },
  {
    "code": "C-3F-3287",
    "x": 2996,
    "y": 1197,
    "width": 68,
    "height": 82
  },
  {
    "code": "C-3F-3284",
    "x": 2712,
    "y": 1197,
    "width": 68,
    "height": 82
  },
  {
    "code": "A-3F-3107",
    "x": 3635,
    "y": 2393,
    "width": 79,
    "height": 70
  },
  {
    "code": "A-3F-3116",
    "x": 3635,
    "y": 2321,
    "width": 78,
    "height": 70
  },
  {
    "code": "B-3F-3114",
    "x": 905,
    "y": 2500,
    "width": 94,
    "height": 58
  },
  {
    "code": "B-3F-3178",
    "x": 1203,
    "y": 2180,
    "width": 74,
    "height": 73
  },
  {
    "code": "B-3F-3216",
    "x": 1139,
    "y": 2606,
    "width": 73,
    "height": 73
  },
  {
    "code": "B-3F-3195",
    "x": 1139,
    "y": 2531,
    "width": 73,
    "height": 73
  },
  {
    "code": "A-3F-3128",
    "x": 3066,
    "y": 2180,
    "width": 70,
    "height": 76
  },
  {
    "code": "A-3F-3127",
    "x": 2995,
    "y": 2180,
    "width": 70,
    "height": 76
  },
  {
    "code": "A-3F-3135",
    "x": 3919,
    "y": 2180,
    "width": 69,
    "height": 76
  },
  {
    "code": "A-3F-3134",
    "x": 3848,
    "y": 2180,
    "width": 69,
    "height": 76
  },
  {
    "code": "A-3F-3131",
    "x": 3564,
    "y": 2180,
    "width": 69,
    "height": 76
  },
  {
    "code": "A-3F-3140",
    "x": 3919,
    "y": 2102,
    "width": 69,
    "height": 76
  },
  {
    "code": "A-3F-3141",
    "x": 3848,
    "y": 2102,
    "width": 69,
    "height": 76
  },
  {
    "code": "A-3F-3144",
    "x": 3564,
    "y": 2102,
    "width": 69,
    "height": 76
  },
  {
    "code": "C-3F-3323",
    "x": 2712,
    "y": 984,
    "width": 68,
    "height": 76
  },
  {
    "code": "C-3F-3322",
    "x": 2641,
    "y": 984,
    "width": 68,
    "height": 76
  },
  {
    "code": "C-3F-3350",
    "x": 2712,
    "y": 906,
    "width": 68,
    "height": 76
  },
  {
    "code": "C-3F-3351",
    "x": 2641,
    "y": 906,
    "width": 68,
    "height": 76
  },
  {
    "code": "A-3F-3148",
    "x": 3067,
    "y": 2102,
    "width": 68,
    "height": 75
  },
  {
    "code": "A-3F-3149",
    "x": 2996,
    "y": 2102,
    "width": 68,
    "height": 75
  },
  {
    "code": "A-3F-3152",
    "x": 2712,
    "y": 2102,
    "width": 68,
    "height": 75
  },
  {
    "code": "B-3F-3113",
    "x": 905,
    "y": 2560,
    "width": 94,
    "height": 53
  },
  {
    "code": "A-3F-3114",
    "x": 3848,
    "y": 2320,
    "width": 69,
    "height": 71
  },
  {
    "code": "A-3F-3117",
    "x": 3564,
    "y": 2320,
    "width": 69,
    "height": 71
  },
  {
    "code": "B-3F-3256",
    "x": 1960,
    "y": 2974,
    "width": 51,
    "height": 95
  },
  {
    "code": "A-3F-3109",
    "x": 3848,
    "y": 2393,
    "width": 69,
    "height": 70
  },
  {
    "code": "A-3F-3106",
    "x": 3564,
    "y": 2393,
    "width": 69,
    "height": 70
  },
  {
    "code": "B-3F-3215",
    "x": 1001,
    "y": 2606,
    "width": 67,
    "height": 72
  },
  {
    "code": "A-3F-3125",
    "x": 2281,
    "y": 1972,
    "width": 70,
    "height": 68
  },
  {
    "code": "B-3F-3122",
    "x": 905,
    "y": 1991,
    "width": 94,
    "height": 49
  },
  {
    "code": "C-3F-3345",
    "x": 3434,
    "y": 936,
    "width": 99,
    "height": 46
  },
  {
    "code": "B-3F-3110",
    "x": 905,
    "y": 2742,
    "width": 92,
    "height": 49
  },
  {
    "code": "C-3F-3344",
    "x": 3535,
    "y": 936,
    "width": 97,
    "height": 46
  },
  {
    "code": "B-3F-3109",
    "x": 905,
    "y": 2793,
    "width": 92,
    "height": 47
  },
  {
    "code": "B-3F-3138",
    "x": 681,
    "y": 2180,
    "width": 52,
    "height": 73
  },
  {
    "code": "C-3F-3343",
    "x": 3635,
    "y": 936,
    "width": 78,
    "height": 46
  },
  {
    "code": "A-3F-3124",
    "x": 2712,
    "y": 2180,
    "width": 68,
    "height": 52
  },
  {
    "code": "B-3F-3124",
    "x": 905,
    "y": 1892,
    "width": 71,
    "height": 48
  }
];

export const HOTSPOTS_3F: FloorHotspotData = {
  floor: '3F',
  imageWidth: W,
  imageHeight: H,
  regions: REGIONS,
  stores: STORES,
  facilities: [],
};
