// AUTO-GENERATED by scripts/buildAllHotspots.mjs
// 2F SVG 파싱 + PNG OCR 매칭 결과
// 총 472개 셀 매칭 (디렉터리 2F: 775개)

import { FloorHotspotData } from '@/components/map/ImageOverlayMap';

const W = 4406;
const H = 3077;

const REGIONS: FloorHotspotData['regions'] = [
  {
    "building": "A",
    "polygon": [
      [
        2165,
        1745
      ],
      [
        4372,
        1745
      ],
      [
        4372,
        3060
      ],
      [
        2165,
        3060
      ]
    ]
  },
  {
    "building": "B",
    "polygon": [
      [
        156,
        1630
      ],
      [
        2159,
        1630
      ],
      [
        2159,
        3060
      ],
      [
        156,
        3060
      ]
    ]
  },
  {
    "building": "C",
    "polygon": [
      [
        2165,
        733
      ],
      [
        4370,
        733
      ],
      [
        4370,
        1737
      ],
      [
        2165,
        1737
      ]
    ]
  },
  {
    "building": "N",
    "polygon": [
      [
        2755,
        337
      ],
      [
        3736,
        337
      ],
      [
        3736,
        594
      ],
      [
        2755,
        594
      ]
    ]
  }
] as FloorHotspotData['regions'];

const STORES = [
  {
    "code": "B-2F-2534",
    "x": 1633,
    "y": 1630,
    "width": 105,
    "height": 107
  },
  {
    "code": "B-2F-2511",
    "x": 1101,
    "y": 1630,
    "width": 99,
    "height": 107
  },
  {
    "code": "A-2F-2234",
    "x": 4231,
    "y": 1966,
    "width": 140,
    "height": 74
  },
  {
    "code": "B-2F-2544",
    "x": 297,
    "y": 1630,
    "width": 84,
    "height": 107
  },
  {
    "code": "A-2F-2162",
    "x": 2458,
    "y": 2244,
    "width": 139,
    "height": 64
  },
  {
    "code": "A-2F-2163",
    "x": 2458,
    "y": 2179,
    "width": 139,
    "height": 63
  },
  {
    "code": "B-2F-2369",
    "x": 2023,
    "y": 2473,
    "width": 136,
    "height": 64
  },
  {
    "code": "B-2F-2513",
    "x": 1303,
    "y": 1630,
    "width": 80,
    "height": 107
  },
  {
    "code": "B-2F-2504",
    "x": 877,
    "y": 1630,
    "width": 80,
    "height": 107
  },
  {
    "code": "B-2F-2531",
    "x": 1882,
    "y": 1630,
    "width": 79,
    "height": 107
  },
  {
    "code": "B-2F-2539",
    "x": 755,
    "y": 1630,
    "width": 79,
    "height": 107
  },
  {
    "code": "B-2F-2368",
    "x": 2023,
    "y": 2540,
    "width": 136,
    "height": 62
  },
  {
    "code": "B-2F-2427",
    "x": 2023,
    "y": 2244,
    "width": 136,
    "height": 62
  },
  {
    "code": "B-2F-2428",
    "x": 2023,
    "y": 2179,
    "width": 136,
    "height": 62
  },
  {
    "code": "B-2F-2540",
    "x": 675,
    "y": 1630,
    "width": 78,
    "height": 107
  },
  {
    "code": "B-2F-2541",
    "x": 594,
    "y": 1630,
    "width": 78,
    "height": 107
  },
  {
    "code": "B-2F-2543",
    "x": 383,
    "y": 1630,
    "width": 76,
    "height": 107
  },
  {
    "code": "A-2F-2262",
    "x": 2457,
    "y": 1745,
    "width": 140,
    "height": 58
  },
  {
    "code": "C-2F-2172",
    "x": 2311,
    "y": 1421,
    "width": 71,
    "height": 111
  },
  {
    "code": "C-2F-2173",
    "x": 2239,
    "y": 1421,
    "width": 70,
    "height": 111
  },
  {
    "code": "C-2F-2175",
    "x": 2165,
    "y": 1630,
    "width": 72,
    "height": 107
  },
  {
    "code": "C-2F-2174",
    "x": 2168,
    "y": 1421,
    "width": 69,
    "height": 111
  },
  {
    "code": "C-2F-2177",
    "x": 2311,
    "y": 1630,
    "width": 71,
    "height": 107
  },
  {
    "code": "B-2F-2546",
    "x": 156,
    "y": 1630,
    "width": 71,
    "height": 107
  },
  {
    "code": "C-2F-2171",
    "x": 2384,
    "y": 1421,
    "width": 68,
    "height": 111
  },
  {
    "code": "C-2F-2176",
    "x": 2239,
    "y": 1630,
    "width": 70,
    "height": 107
  },
  {
    "code": "A-2F-2109",
    "x": 4225,
    "y": 2658,
    "width": 146,
    "height": 51
  },
  {
    "code": "B-2F-2530",
    "x": 2023,
    "y": 1630,
    "width": 69,
    "height": 107
  },
  {
    "code": "B-2F-2532",
    "x": 1811,
    "y": 1630,
    "width": 69,
    "height": 107
  },
  {
    "code": "B-2F-2533",
    "x": 1740,
    "y": 1630,
    "width": 69,
    "height": 107
  },
  {
    "code": "B-2F-2535",
    "x": 1456,
    "y": 1630,
    "width": 69,
    "height": 107
  },
  {
    "code": "B-2F-2536",
    "x": 1385,
    "y": 1630,
    "width": 69,
    "height": 107
  },
  {
    "code": "B-2F-2537",
    "x": 1030,
    "y": 1630,
    "width": 69,
    "height": 107
  },
  {
    "code": "B-2F-2538",
    "x": 959,
    "y": 1630,
    "width": 69,
    "height": 107
  },
  {
    "code": "A-2F-2110",
    "x": 4225,
    "y": 2606,
    "width": 146,
    "height": 50
  },
  {
    "code": "A-2F-2261",
    "x": 2457,
    "y": 1805,
    "width": 140,
    "height": 52
  },
  {
    "code": "C-2F-2178",
    "x": 2384,
    "y": 1630,
    "width": 68,
    "height": 107
  },
  {
    "code": "B-2F-2460",
    "x": 1101,
    "y": 1965,
    "width": 99,
    "height": 73
  },
  {
    "code": "A-2F-2235",
    "x": 4231,
    "y": 1912,
    "width": 141,
    "height": 51
  },
  {
    "code": "A-2F-2236",
    "x": 4231,
    "y": 1859,
    "width": 141,
    "height": 51
  },
  {
    "code": "A-2F-2291",
    "x": 4231,
    "y": 1806,
    "width": 141,
    "height": 51
  },
  {
    "code": "A-2F-2260",
    "x": 2457,
    "y": 1859,
    "width": 140,
    "height": 51
  },
  {
    "code": "B-2F-2542",
    "x": 461,
    "y": 1630,
    "width": 66,
    "height": 107
  },
  {
    "code": "B-2F-2529",
    "x": 2094,
    "y": 1630,
    "width": 65,
    "height": 107
  },
  {
    "code": "B-2F-2489",
    "x": 1101,
    "y": 1893,
    "width": 99,
    "height": 70
  },
  {
    "code": "A-2F-2147",
    "x": 4054,
    "y": 2391,
    "width": 81,
    "height": 80
  },
  {
    "code": "A-2F-2148",
    "x": 4054,
    "y": 2310,
    "width": 81,
    "height": 80
  },
  {
    "code": "B-2F-2370",
    "x": 1847,
    "y": 2550,
    "width": 117,
    "height": 52
  },
  {
    "code": "B-2F-2341",
    "x": 835,
    "y": 2746,
    "width": 87,
    "height": 69
  },
  {
    "code": "B-2F-2459",
    "x": 1017,
    "y": 1965,
    "width": 82,
    "height": 73
  },
  {
    "code": "B-2F-2426",
    "x": 1847,
    "y": 2179,
    "width": 117,
    "height": 51
  },
  {
    "code": "C-2F-2135",
    "x": 4107,
    "y": 968,
    "width": 66,
    "height": 89
  },
  {
    "code": "C-2F-2125",
    "x": 3507,
    "y": 968,
    "width": 66,
    "height": 89
  },
  {
    "code": "C-2F-2112",
    "x": 2523,
    "y": 1115,
    "width": 74,
    "height": 79
  },
  {
    "code": "B-2F-2387",
    "x": 594,
    "y": 2392,
    "width": 79,
    "height": 73
  },
  {
    "code": "B-2F-2490",
    "x": 1017,
    "y": 1893,
    "width": 82,
    "height": 70
  },
  {
    "code": "B-2F-2411",
    "x": 594,
    "y": 2178,
    "width": 78,
    "height": 73
  },
  {
    "code": "B-2F-2450",
    "x": 594,
    "y": 2104,
    "width": 79,
    "height": 72
  },
  {
    "code": "B-2F-2310",
    "x": 990,
    "y": 2797,
    "width": 104,
    "height": 54
  },
  {
    "code": "C-2F-2124",
    "x": 3170,
    "y": 983,
    "width": 72,
    "height": 78
  },
  {
    "code": "C-2F-2104",
    "x": 3096,
    "y": 1115,
    "width": 71,
    "height": 79
  },
  {
    "code": "C-2F-2123",
    "x": 3096,
    "y": 983,
    "width": 71,
    "height": 79
  },
  {
    "code": "C-2F-2168",
    "x": 2311,
    "y": 1115,
    "width": 70,
    "height": 80
  },
  {
    "code": "C-2F-2169",
    "x": 2239,
    "y": 1115,
    "width": 70,
    "height": 80
  },
  {
    "code": "C-2F-2164",
    "x": 2311,
    "y": 982,
    "width": 70,
    "height": 80
  },
  {
    "code": "C-2F-2165",
    "x": 2239,
    "y": 982,
    "width": 70,
    "height": 80
  },
  {
    "code": "B-2F-2451",
    "x": 461.9,
    "y": 2103,
    "width": 65.1,
    "height": 86
  },
  {
    "code": "B-2F-2518",
    "x": 1527,
    "y": 1630,
    "width": 52,
    "height": 107
  },
  {
    "code": "B-2F-2309",
    "x": 990,
    "y": 2853,
    "width": 63,
    "height": 88
  },
  {
    "code": "B-2F-2496",
    "x": 594,
    "y": 1893,
    "width": 79,
    "height": 70
  },
  {
    "code": "C-2F-2167",
    "x": 2383,
    "y": 1115,
    "width": 69,
    "height": 80
  },
  {
    "code": "C-2F-2170",
    "x": 2168,
    "y": 1115,
    "width": 69,
    "height": 80
  },
  {
    "code": "B-2F-2410",
    "x": 594,
    "y": 2320,
    "width": 78,
    "height": 70
  },
  {
    "code": "B-2F-2425",
    "x": 1740,
    "y": 2178,
    "width": 105,
    "height": 52
  },
  {
    "code": "B-2F-2453",
    "x": 594,
    "y": 1965,
    "width": 78,
    "height": 70
  },
  {
    "code": "C-2F-2154",
    "x": 2785,
    "y": 803,
    "width": 82,
    "height": 66
  },
  {
    "code": "B-2F-2371",
    "x": 1740,
    "y": 2550,
    "width": 104,
    "height": 52
  },
  {
    "code": "C-2F-2163",
    "x": 2384,
    "y": 982,
    "width": 68,
    "height": 79
  },
  {
    "code": "C-2F-2166",
    "x": 2168,
    "y": 982,
    "width": 68,
    "height": 79
  },
  {
    "code": "A-2F-2138",
    "x": 3255,
    "y": 2391,
    "width": 66,
    "height": 80
  },
  {
    "code": "A-2F-2157",
    "x": 3255,
    "y": 2310,
    "width": 66,
    "height": 80
  },
  {
    "code": "A-2F-2131",
    "x": 2655,
    "y": 2559,
    "width": 119,
    "height": 44
  },
  {
    "code": "C-2F-2102",
    "x": 3507,
    "y": 1115,
    "width": 66,
    "height": 79
  },
  {
    "code": "C-2F-2111",
    "x": 2655,
    "y": 1115,
    "width": 66,
    "height": 79
  },
  {
    "code": "B-2F-2322",
    "x": 2023,
    "y": 2818,
    "width": 71,
    "height": 73
  },
  {
    "code": "B-2F-2500",
    "x": 594,
    "y": 1745,
    "width": 78,
    "height": 66
  },
  {
    "code": "A-2F-2164",
    "x": 2655,
    "y": 2179,
    "width": 119,
    "height": 43
  },
  {
    "code": "A-2F-2274",
    "x": 3255,
    "y": 1745,
    "width": 66,
    "height": 77
  },
  {
    "code": "A-2F-2263",
    "x": 2655,
    "y": 1745,
    "width": 66,
    "height": 77
  },
  {
    "code": "C-2F-2116",
    "x": 2655,
    "y": 983,
    "width": 65,
    "height": 78
  },
  {
    "code": "B-2F-2297",
    "x": 1899,
    "y": 2961,
    "width": 51,
    "height": 99
  },
  {
    "code": "B-2F-2305",
    "x": 1474,
    "y": 2961,
    "width": 51,
    "height": 99
  },
  {
    "code": "B-2F-2308",
    "x": 1260,
    "y": 2962,
    "width": 52,
    "height": 97
  },
  {
    "code": "B-2F-2364",
    "x": 2023,
    "y": 2604,
    "width": 71,
    "height": 71
  },
  {
    "code": "B-2F-2458",
    "x": 945,
    "y": 1965,
    "width": 69,
    "height": 73
  },
  {
    "code": "A-2F-2290",
    "x": 4108,
    "y": 1745,
    "width": 65,
    "height": 77
  },
  {
    "code": "B-2F-2295",
    "x": 2006,
    "y": 2962,
    "width": 51,
    "height": 98
  },
  {
    "code": "B-2F-2300",
    "x": 1740,
    "y": 2962,
    "width": 51,
    "height": 98
  },
  {
    "code": "B-2F-2302",
    "x": 1633,
    "y": 2962,
    "width": 51,
    "height": 98
  },
  {
    "code": "B-2F-2307",
    "x": 1367,
    "y": 2962,
    "width": 51,
    "height": 98
  },
  {
    "code": "C-2F-2114",
    "x": 2458,
    "y": 983,
    "width": 63,
    "height": 79
  },
  {
    "code": "B-2F-2327",
    "x": 2023,
    "y": 2746,
    "width": 71,
    "height": 70
  },
  {
    "code": "B-2F-2457",
    "x": 875,
    "y": 1965,
    "width": 68,
    "height": 73
  },
  {
    "code": "C-2F-2115",
    "x": 2523,
    "y": 914,
    "width": 74,
    "height": 67
  },
  {
    "code": "B-2F-2294",
    "x": 2059,
    "y": 2962,
    "width": 51,
    "height": 97
  },
  {
    "code": "B-2F-2298",
    "x": 1846,
    "y": 2962,
    "width": 51,
    "height": 97
  },
  {
    "code": "B-2F-2299",
    "x": 1793,
    "y": 2962,
    "width": 51,
    "height": 97
  },
  {
    "code": "B-2F-2303",
    "x": 1580,
    "y": 2962,
    "width": 51,
    "height": 97
  },
  {
    "code": "B-2F-2304",
    "x": 1527,
    "y": 2962,
    "width": 51,
    "height": 97
  },
  {
    "code": "B-2F-2491",
    "x": 945,
    "y": 1893,
    "width": 70,
    "height": 70
  },
  {
    "code": "B-2F-2296",
    "x": 1953,
    "y": 2962,
    "width": 50,
    "height": 97
  },
  {
    "code": "B-2F-2301",
    "x": 1687,
    "y": 2962,
    "width": 50,
    "height": 97
  },
  {
    "code": "B-2F-2306",
    "x": 1421,
    "y": 2962,
    "width": 50,
    "height": 97
  },
  {
    "code": "A-2F-2204",
    "x": 2528,
    "y": 2106,
    "width": 69,
    "height": 70
  },
  {
    "code": "B-2F-2432",
    "x": 2023,
    "y": 2106,
    "width": 69,
    "height": 70
  },
  {
    "code": "A-2F-2226",
    "x": 3663,
    "y": 1965,
    "width": 69,
    "height": 70
  },
  {
    "code": "A-2F-2224",
    "x": 3521,
    "y": 1965,
    "width": 69,
    "height": 70
  },
  {
    "code": "A-2F-2223",
    "x": 3450,
    "y": 1965,
    "width": 69,
    "height": 70
  },
  {
    "code": "B-2F-2472",
    "x": 2023,
    "y": 1965,
    "width": 69,
    "height": 70
  },
  {
    "code": "A-2F-2247",
    "x": 3450,
    "y": 1893,
    "width": 69,
    "height": 70
  },
  {
    "code": "B-2F-2477",
    "x": 2023,
    "y": 1893,
    "width": 69,
    "height": 70
  },
  {
    "code": "A-2F-2205",
    "x": 2458,
    "y": 2106,
    "width": 68,
    "height": 71
  },
  {
    "code": "A-2F-2211",
    "x": 2528,
    "y": 1966,
    "width": 69,
    "height": 69
  },
  {
    "code": "A-2F-2244",
    "x": 3664,
    "y": 1893,
    "width": 68,
    "height": 70
  },
  {
    "code": "A-2F-2245",
    "x": 3593,
    "y": 1893,
    "width": 68,
    "height": 70
  },
  {
    "code": "A-2F-2246",
    "x": 3522,
    "y": 1893,
    "width": 68,
    "height": 70
  },
  {
    "code": "B-2F-2492",
    "x": 875,
    "y": 1893,
    "width": 68,
    "height": 70
  },
  {
    "code": "C-2F-2140",
    "x": 3170,
    "y": 914,
    "width": 72,
    "height": 66
  },
  {
    "code": "A-2F-2123",
    "x": 3255,
    "y": 2532,
    "width": 66,
    "height": 71
  },
  {
    "code": "A-2F-2172",
    "x": 3255,
    "y": 2178,
    "width": 66,
    "height": 71
  },
  {
    "code": "A-2F-2193",
    "x": 3255,
    "y": 2106,
    "width": 66,
    "height": 71
  },
  {
    "code": "A-2F-2203",
    "x": 2655,
    "y": 2106,
    "width": 66,
    "height": 71
  },
  {
    "code": "A-2F-2207",
    "x": 2311,
    "y": 2106,
    "width": 71,
    "height": 66
  },
  {
    "code": "C-2F-2141",
    "x": 3096,
    "y": 914,
    "width": 71,
    "height": 66
  },
  {
    "code": "B-2F-2323",
    "x": 2095,
    "y": 2818,
    "width": 64,
    "height": 73
  },
  {
    "code": "B-2F-2321",
    "x": 1900,
    "y": 2818,
    "width": 64,
    "height": 73
  },
  {
    "code": "B-2F-2461",
    "x": 1301,
    "y": 1965,
    "width": 64,
    "height": 73
  },
  {
    "code": "B-2F-2353",
    "x": 1302,
    "y": 2604,
    "width": 63,
    "height": 74
  },
  {
    "code": "C-2F-2134",
    "x": 4054,
    "y": 968,
    "width": 52,
    "height": 89
  },
  {
    "code": "A-2F-2222",
    "x": 3255,
    "y": 1965,
    "width": 66,
    "height": 70
  },
  {
    "code": "A-2F-2212",
    "x": 2655,
    "y": 1965,
    "width": 66,
    "height": 70
  },
  {
    "code": "A-2F-2248",
    "x": 3255,
    "y": 1893,
    "width": 66,
    "height": 70
  },
  {
    "code": "A-2F-2258",
    "x": 2655,
    "y": 1893,
    "width": 66,
    "height": 70
  },
  {
    "code": "A-2F-2182",
    "x": 4108,
    "y": 2178,
    "width": 65,
    "height": 71
  },
  {
    "code": "B-2F-2431",
    "x": 2094,
    "y": 2106,
    "width": 65,
    "height": 71
  },
  {
    "code": "A-2F-2208",
    "x": 2311,
    "y": 1970,
    "width": 71,
    "height": 65
  },
  {
    "code": "B-2F-2348",
    "x": 875,
    "y": 2605,
    "width": 64,
    "height": 72
  },
  {
    "code": "B-2F-2394",
    "x": 1302,
    "y": 2392,
    "width": 63,
    "height": 73
  },
  {
    "code": "B-2F-2471",
    "x": 1901,
    "y": 1965,
    "width": 63,
    "height": 73
  },
  {
    "code": "A-2F-2130",
    "x": 2776,
    "y": 2559,
    "width": 104,
    "height": 44
  },
  {
    "code": "A-2F-2183",
    "x": 4108,
    "y": 2106,
    "width": 65,
    "height": 70
  },
  {
    "code": "A-2F-2233",
    "x": 4108,
    "y": 1965,
    "width": 65,
    "height": 70
  },
  {
    "code": "A-2F-2237",
    "x": 4108,
    "y": 1893,
    "width": 65,
    "height": 70
  },
  {
    "code": "B-2F-2476",
    "x": 2094,
    "y": 1893,
    "width": 65,
    "height": 70
  },
  {
    "code": "B-2F-2328",
    "x": 1900,
    "y": 2745,
    "width": 64,
    "height": 71
  },
  {
    "code": "B-2F-2365",
    "x": 2095,
    "y": 2604,
    "width": 64,
    "height": 71
  },
  {
    "code": "B-2F-2363",
    "x": 1900,
    "y": 2604,
    "width": 64,
    "height": 71
  },
  {
    "code": "C-2F-2133",
    "x": 4001,
    "y": 968,
    "width": 51,
    "height": 89
  },
  {
    "code": "C-2F-2132",
    "x": 3948,
    "y": 968,
    "width": 51,
    "height": 89
  },
  {
    "code": "C-2F-2129",
    "x": 3734,
    "y": 968,
    "width": 51,
    "height": 89
  },
  {
    "code": "C-2F-2128",
    "x": 3681,
    "y": 968,
    "width": 51,
    "height": 89
  },
  {
    "code": "C-2F-2127",
    "x": 3628,
    "y": 968,
    "width": 51,
    "height": 89
  },
  {
    "code": "C-2F-2126",
    "x": 3575,
    "y": 968,
    "width": 51,
    "height": 89
  },
  {
    "code": "B-2F-2339",
    "x": 1177,
    "y": 2746,
    "width": 56,
    "height": 81
  },
  {
    "code": "A-2F-2165",
    "x": 2776,
    "y": 2179,
    "width": 105,
    "height": 43
  },
  {
    "code": "A-2F-2206",
    "x": 2384,
    "y": 2106,
    "width": 68,
    "height": 66
  },
  {
    "code": "A-2F-2209",
    "x": 2384,
    "y": 1970,
    "width": 69,
    "height": 65
  },
  {
    "code": "B-2F-2525",
    "x": 2023,
    "y": 1745,
    "width": 69,
    "height": 65
  },
  {
    "code": "B-2F-2338",
    "x": 1301,
    "y": 2746,
    "width": 64,
    "height": 70
  },
  {
    "code": "B-2F-2433",
    "x": 1900,
    "y": 2106,
    "width": 64,
    "height": 70
  },
  {
    "code": "B-2F-2473",
    "x": 2095,
    "y": 1965,
    "width": 64,
    "height": 70
  },
  {
    "code": "B-2F-2478",
    "x": 1900,
    "y": 1893,
    "width": 64,
    "height": 70
  },
  {
    "code": "B-2F-2488",
    "x": 1301,
    "y": 1893,
    "width": 64,
    "height": 70
  },
  {
    "code": "B-2F-2418",
    "x": 1303,
    "y": 2179,
    "width": 62,
    "height": 72
  },
  {
    "code": "B-2F-2313",
    "x": 728,
    "y": 2972,
    "width": 51,
    "height": 87
  },
  {
    "code": "B-2F-2383",
    "x": 875,
    "y": 2533,
    "width": 64,
    "height": 69
  },
  {
    "code": "B-2F-2326",
    "x": 2096,
    "y": 2746,
    "width": 63,
    "height": 70
  },
  {
    "code": "B-2F-2403",
    "x": 1303,
    "y": 2320,
    "width": 62,
    "height": 70
  },
  {
    "code": "B-2F-2443",
    "x": 1303,
    "y": 2106,
    "width": 62,
    "height": 70
  },
  {
    "code": "C-2F-2158",
    "x": 3426,
    "y": 783,
    "width": 50,
    "height": 86
  },
  {
    "code": "B-2F-2352",
    "x": 1160,
    "y": 2604,
    "width": 58,
    "height": 74
  },
  {
    "code": "B-2F-2526",
    "x": 2094,
    "y": 1745,
    "width": 65,
    "height": 66
  },
  {
    "code": "C-2F-2148",
    "x": 2655,
    "y": 914,
    "width": 65,
    "height": 66
  },
  {
    "code": "C-2F-2149",
    "x": 2458,
    "y": 913,
    "width": 63,
    "height": 68
  },
  {
    "code": "B-2F-2378",
    "x": 1303,
    "y": 2533,
    "width": 62,
    "height": 69
  },
  {
    "code": "C-2F-2150",
    "x": 2458,
    "y": 803,
    "width": 64,
    "height": 66
  },
  {
    "code": "C-2F-2105",
    "x": 3041,
    "y": 1115,
    "width": 53,
    "height": 79
  },
  {
    "code": "C-2F-2122",
    "x": 3041,
    "y": 983,
    "width": 53,
    "height": 79
  },
  {
    "code": "A-2F-2104",
    "x": 3893,
    "y": 2391,
    "width": 52,
    "height": 80
  },
  {
    "code": "A-2F-2151",
    "x": 3893,
    "y": 2310,
    "width": 52,
    "height": 80
  },
  {
    "code": "A-2F-2159",
    "x": 3148,
    "y": 2310,
    "width": 52,
    "height": 80
  },
  {
    "code": "A-2F-2161",
    "x": 3041,
    "y": 2310,
    "width": 52,
    "height": 80
  },
  {
    "code": "C-2F-2120",
    "x": 2882,
    "y": 982,
    "width": 52,
    "height": 80
  },
  {
    "code": "C-2F-2106",
    "x": 2936,
    "y": 1115,
    "width": 52,
    "height": 79
  },
  {
    "code": "C-2F-2107",
    "x": 2882,
    "y": 1115,
    "width": 52,
    "height": 79
  },
  {
    "code": "C-2F-2121",
    "x": 2936,
    "y": 983,
    "width": 52,
    "height": 79
  },
  {
    "code": "B-2F-2512",
    "x": 1303,
    "y": 1745,
    "width": 62,
    "height": 66
  },
  {
    "code": "A-2F-2145",
    "x": 3948,
    "y": 2391,
    "width": 51,
    "height": 80
  },
  {
    "code": "A-2F-2142",
    "x": 3735,
    "y": 2391,
    "width": 51,
    "height": 80
  },
  {
    "code": "A-2F-2140",
    "x": 3628,
    "y": 2391,
    "width": 51,
    "height": 80
  },
  {
    "code": "A-2F-2150",
    "x": 3948,
    "y": 2310,
    "width": 51,
    "height": 80
  },
  {
    "code": "A-2F-2155",
    "x": 3628,
    "y": 2310,
    "width": 51,
    "height": 80
  },
  {
    "code": "A-2F-2143",
    "x": 3788,
    "y": 2392,
    "width": 52,
    "height": 78
  },
  {
    "code": "A-2F-2139",
    "x": 3574,
    "y": 2392,
    "width": 52,
    "height": 78
  },
  {
    "code": "A-2F-2134",
    "x": 3041,
    "y": 2392,
    "width": 52,
    "height": 78
  },
  {
    "code": "A-2F-2152",
    "x": 3788,
    "y": 2311,
    "width": 52,
    "height": 78
  },
  {
    "code": "A-2F-2156",
    "x": 3574,
    "y": 2311,
    "width": 52,
    "height": 78
  },
  {
    "code": "B-2F-2505",
    "x": 877,
    "y": 1745,
    "width": 62,
    "height": 65
  },
  {
    "code": "A-2F-2153",
    "x": 3735,
    "y": 2310,
    "width": 51,
    "height": 79
  },
  {
    "code": "A-2F-2160",
    "x": 3095,
    "y": 2310,
    "width": 51,
    "height": 79
  },
  {
    "code": "C-2F-2100",
    "x": 3628,
    "y": 1115,
    "width": 51,
    "height": 79
  },
  {
    "code": "C-2F-2101",
    "x": 3575,
    "y": 1115,
    "width": 51,
    "height": 79
  },
  {
    "code": "C-2F-2108",
    "x": 2829,
    "y": 1115,
    "width": 51,
    "height": 79
  },
  {
    "code": "C-2F-2109",
    "x": 2776,
    "y": 1115,
    "width": 51,
    "height": 79
  },
  {
    "code": "C-2F-2119",
    "x": 2829,
    "y": 983,
    "width": 51,
    "height": 79
  },
  {
    "code": "C-2F-2118",
    "x": 2776,
    "y": 983,
    "width": 51,
    "height": 79
  },
  {
    "code": "C-2F-2117",
    "x": 2723,
    "y": 983,
    "width": 51,
    "height": 79
  },
  {
    "code": "A-2F-2289",
    "x": 4054,
    "y": 1745,
    "width": 52,
    "height": 77
  },
  {
    "code": "A-2F-2284",
    "x": 3788,
    "y": 1745,
    "width": 52,
    "height": 77
  },
  {
    "code": "A-2F-2281",
    "x": 3628,
    "y": 1745,
    "width": 52,
    "height": 77
  },
  {
    "code": "A-2F-2278",
    "x": 3468,
    "y": 1745,
    "width": 52,
    "height": 77
  },
  {
    "code": "A-2F-2271",
    "x": 3095,
    "y": 1745,
    "width": 52,
    "height": 77
  },
  {
    "code": "A-2F-2270",
    "x": 3041,
    "y": 1745,
    "width": 52,
    "height": 77
  },
  {
    "code": "A-2F-2268",
    "x": 2936,
    "y": 1745,
    "width": 52,
    "height": 77
  },
  {
    "code": "B-2F-2379",
    "x": 1160,
    "y": 2533,
    "width": 58,
    "height": 69
  },
  {
    "code": "A-2F-2146",
    "x": 4001,
    "y": 2392,
    "width": 51,
    "height": 78
  },
  {
    "code": "A-2F-2137",
    "x": 3202,
    "y": 2392,
    "width": 51,
    "height": 78
  },
  {
    "code": "A-2F-2136",
    "x": 3149,
    "y": 2392,
    "width": 51,
    "height": 78
  },
  {
    "code": "A-2F-2135",
    "x": 3095,
    "y": 2392,
    "width": 51,
    "height": 78
  },
  {
    "code": "A-2F-2149",
    "x": 4001,
    "y": 2311,
    "width": 51,
    "height": 78
  },
  {
    "code": "A-2F-2158",
    "x": 3202,
    "y": 2311,
    "width": 51,
    "height": 78
  },
  {
    "code": "B-2F-2524",
    "x": 1900,
    "y": 1745,
    "width": 61,
    "height": 65
  },
  {
    "code": "C-2F-2151",
    "x": 2554,
    "y": 803,
    "width": 59,
    "height": 67
  },
  {
    "code": "C-2F-2157",
    "x": 3158,
    "y": 802,
    "width": 58,
    "height": 68
  },
  {
    "code": "B-2F-2906",
    "x": 332,
    "y": 1893,
    "width": 93,
    "height": 45
  },
  {
    "code": "A-2F-2288",
    "x": 4001,
    "y": 1745,
    "width": 51,
    "height": 77
  },
  {
    "code": "A-2F-2287",
    "x": 3948,
    "y": 1745,
    "width": 51,
    "height": 77
  },
  {
    "code": "A-2F-2286",
    "x": 3894,
    "y": 1745,
    "width": 51,
    "height": 77
  },
  {
    "code": "A-2F-2283",
    "x": 3735,
    "y": 1745,
    "width": 51,
    "height": 77
  },
  {
    "code": "A-2F-2282",
    "x": 3682,
    "y": 1745,
    "width": 51,
    "height": 77
  },
  {
    "code": "A-2F-2280",
    "x": 3575,
    "y": 1745,
    "width": 51,
    "height": 77
  },
  {
    "code": "A-2F-2279",
    "x": 3522,
    "y": 1745,
    "width": 51,
    "height": 77
  },
  {
    "code": "A-2F-2273",
    "x": 3202,
    "y": 1745,
    "width": 51,
    "height": 77
  },
  {
    "code": "A-2F-2272",
    "x": 3149,
    "y": 1745,
    "width": 51,
    "height": 77
  },
  {
    "code": "A-2F-2267",
    "x": 2883,
    "y": 1745,
    "width": 51,
    "height": 77
  },
  {
    "code": "A-2F-2266",
    "x": 2829,
    "y": 1745,
    "width": 51,
    "height": 77
  },
  {
    "code": "A-2F-2265",
    "x": 2776,
    "y": 1745,
    "width": 51,
    "height": 77
  },
  {
    "code": "A-2F-2264",
    "x": 2723,
    "y": 1745,
    "width": 51,
    "height": 77
  },
  {
    "code": "B-2F-2347",
    "x": 781,
    "y": 2604,
    "width": 53,
    "height": 74
  },
  {
    "code": "B-2F-2390",
    "x": 781,
    "y": 2392,
    "width": 53,
    "height": 73
  },
  {
    "code": "B-2F-2528",
    "x": 617,
    "y": 2532,
    "width": 55,
    "height": 70
  },
  {
    "code": "B-2F-2357",
    "x": 1527,
    "y": 2604,
    "width": 52,
    "height": 74
  },
  {
    "code": "B-2F-2355",
    "x": 1420,
    "y": 2604,
    "width": 52,
    "height": 74
  },
  {
    "code": "C-2F-2153",
    "x": 2700,
    "y": 803,
    "width": 58,
    "height": 66
  },
  {
    "code": "C-2F-2152",
    "x": 2640,
    "y": 803,
    "width": 58,
    "height": 66
  },
  {
    "code": "B-2F-2319",
    "x": 1793,
    "y": 2818,
    "width": 52,
    "height": 73
  },
  {
    "code": "B-2F-2315",
    "x": 1527,
    "y": 2818,
    "width": 52,
    "height": 73
  },
  {
    "code": "B-2F-2398",
    "x": 1527,
    "y": 2392,
    "width": 52,
    "height": 73
  },
  {
    "code": "B-2F-2393",
    "x": 981,
    "y": 2392,
    "width": 52,
    "height": 73
  },
  {
    "code": "B-2F-2417",
    "x": 981,
    "y": 2178,
    "width": 52,
    "height": 73
  },
  {
    "code": "B-2F-2414",
    "x": 781,
    "y": 2178,
    "width": 52,
    "height": 73
  },
  {
    "code": "B-2F-2444",
    "x": 981,
    "y": 2103,
    "width": 52,
    "height": 73
  },
  {
    "code": "B-2F-2465",
    "x": 1527,
    "y": 1965,
    "width": 52,
    "height": 73
  },
  {
    "code": "B-2F-2463",
    "x": 1420,
    "y": 1965,
    "width": 52,
    "height": 73
  },
  {
    "code": "B-2F-2356",
    "x": 1474,
    "y": 2604,
    "width": 51,
    "height": 74
  },
  {
    "code": "B-2F-2354",
    "x": 1367,
    "y": 2604,
    "width": 51,
    "height": 74
  },
  {
    "code": "B-2F-2351",
    "x": 1047,
    "y": 2604,
    "width": 51,
    "height": 74
  },
  {
    "code": "B-2F-2350",
    "x": 994,
    "y": 2604,
    "width": 51,
    "height": 74
  },
  {
    "code": "B-2F-2349",
    "x": 941,
    "y": 2604,
    "width": 51,
    "height": 74
  },
  {
    "code": "B-2F-2346",
    "x": 728,
    "y": 2604,
    "width": 51,
    "height": 74
  },
  {
    "code": "B-2F-2358",
    "x": 1632,
    "y": 2604,
    "width": 53,
    "height": 71
  },
  {
    "code": "A-2F-2128",
    "x": 2935,
    "y": 2532,
    "width": 53,
    "height": 71
  },
  {
    "code": "B-2F-2407",
    "x": 781,
    "y": 2319,
    "width": 53,
    "height": 71
  },
  {
    "code": "B-2F-2452",
    "x": 474,
    "y": 1965,
    "width": 53,
    "height": 71
  },
  {
    "code": "B-2F-2333",
    "x": 1632,
    "y": 2744.9,
    "width": 53,
    "height": 71.1
  },
  {
    "code": "B-2F-2320",
    "x": 1847,
    "y": 2818,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2318",
    "x": 1740,
    "y": 2818,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2317",
    "x": 1687,
    "y": 2818,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2314",
    "x": 1474,
    "y": 2818,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2312",
    "x": 1367,
    "y": 2818,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2397",
    "x": 1474,
    "y": 2392,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2395",
    "x": 1367,
    "y": 2392,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2389",
    "x": 728,
    "y": 2392,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2420",
    "x": 1421,
    "y": 2178,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2419",
    "x": 1367,
    "y": 2178,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2416",
    "x": 928,
    "y": 2178,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2413",
    "x": 728,
    "y": 2178,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2412",
    "x": 675,
    "y": 2178,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2448",
    "x": 728,
    "y": 2103,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2470",
    "x": 1847,
    "y": 1965,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2469",
    "x": 1794,
    "y": 1965,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2468",
    "x": 1740,
    "y": 1965,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2467",
    "x": 1687,
    "y": 1965,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2466",
    "x": 1633,
    "y": 1965,
    "width": 51,
    "height": 73
  },
  {
    "code": "B-2F-2464",
    "x": 1474,
    "y": 1965,
    "width": 51,
    "height": 73
  },
  {
    "code": "C-2F-2179",
    "x": 3398,
    "y": 1120,
    "width": 61,
    "height": 61
  },
  {
    "code": "C-2F-2181",
    "x": 3398,
    "y": 995,
    "width": 61,
    "height": 61
  },
  {
    "code": "A-2F-2187",
    "x": 3893,
    "y": 2106,
    "width": 53,
    "height": 70
  },
  {
    "code": "A-2F-2242",
    "x": 3787,
    "y": 1893,
    "width": 53,
    "height": 70
  },
  {
    "code": "B-2F-2493",
    "x": 781,
    "y": 1893,
    "width": 53,
    "height": 70
  },
  {
    "code": "B-2F-2497",
    "x": 474,
    "y": 1893,
    "width": 53,
    "height": 70
  },
  {
    "code": "B-2F-2499",
    "x": 471,
    "y": 1745,
    "width": 56,
    "height": 66
  },
  {
    "code": "B-2F-2334",
    "x": 1527,
    "y": 2745,
    "width": 52,
    "height": 71
  },
  {
    "code": "B-2F-2362",
    "x": 1846,
    "y": 2604,
    "width": 52,
    "height": 71
  },
  {
    "code": "B-2F-2361",
    "x": 1793,
    "y": 2604,
    "width": 52,
    "height": 71
  },
  {
    "code": "A-2F-2115",
    "x": 3893,
    "y": 2532,
    "width": 52,
    "height": 71
  },
  {
    "code": "A-2F-2125",
    "x": 3148,
    "y": 2532,
    "width": 52,
    "height": 71
  },
  {
    "code": "B-2F-2374",
    "x": 1527,
    "y": 2532,
    "width": 52,
    "height": 71
  },
  {
    "code": "B-2F-2404",
    "x": 981,
    "y": 2319,
    "width": 52,
    "height": 71
  },
  {
    "code": "A-2F-2181",
    "x": 4054,
    "y": 2178,
    "width": 52,
    "height": 71
  },
  {
    "code": "A-2F-2179",
    "x": 3947,
    "y": 2178,
    "width": 52,
    "height": 71
  },
  {
    "code": "A-2F-2173",
    "x": 3574,
    "y": 2178,
    "width": 52,
    "height": 71
  },
  {
    "code": "A-2F-2170",
    "x": 3148,
    "y": 2178,
    "width": 52,
    "height": 71
  },
  {
    "code": "A-2F-2197",
    "x": 3041,
    "y": 2106,
    "width": 52,
    "height": 71
  },
  {
    "code": "A-2F-2198",
    "x": 2936,
    "y": 2106,
    "width": 52,
    "height": 71
  },
  {
    "code": "B-2F-2439",
    "x": 1527,
    "y": 2106,
    "width": 52,
    "height": 71
  },
  {
    "code": "A-2F-2232",
    "x": 4054,
    "y": 1965,
    "width": 52,
    "height": 71
  },
  {
    "code": "A-2F-2229",
    "x": 3893,
    "y": 1965,
    "width": 52,
    "height": 71
  },
  {
    "code": "B-2F-2336",
    "x": 1419.9,
    "y": 2744.9,
    "width": 52,
    "height": 71.1
  },
  {
    "code": "A-2F-2118",
    "x": 3680.9,
    "y": 2531.9,
    "width": 52,
    "height": 71.1
  },
  {
    "code": "A-2F-2121",
    "x": 3520.9,
    "y": 2531.9,
    "width": 52,
    "height": 71.1
  },
  {
    "code": "A-2F-2199",
    "x": 2882,
    "y": 2106,
    "width": 52,
    "height": 71.1
  },
  {
    "code": "A-2F-2200",
    "x": 2829,
    "y": 2106,
    "width": 52,
    "height": 71.1
  },
  {
    "code": "B-2F-2392",
    "x": 928,
    "y": 2392,
    "width": 51,
    "height": 72
  },
  {
    "code": "B-2F-2421",
    "x": 1474,
    "y": 2179,
    "width": 51,
    "height": 72
  },
  {
    "code": "B-2F-2445",
    "x": 928,
    "y": 2104,
    "width": 51,
    "height": 72
  },
  {
    "code": "C-2F-2180",
    "x": 3398,
    "y": 1058,
    "width": 61,
    "height": 60
  },
  {
    "code": "B-2F-2391",
    "x": 876,
    "y": 2392,
    "width": 50,
    "height": 73
  },
  {
    "code": "A-2F-2105",
    "x": 3947,
    "y": 2605,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2103",
    "x": 3788,
    "y": 2605,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2101",
    "x": 3681,
    "y": 2605,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2100",
    "x": 3628,
    "y": 2605,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2116",
    "x": 3788,
    "y": 2533,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2127",
    "x": 3041,
    "y": 2533,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2177",
    "x": 3788,
    "y": 2178,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2168",
    "x": 3041,
    "y": 2179,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2184",
    "x": 4054,
    "y": 2106,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2186",
    "x": 3947,
    "y": 2106,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2188",
    "x": 3788,
    "y": 2106,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2190",
    "x": 3681,
    "y": 2106,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2192",
    "x": 3574,
    "y": 2106,
    "width": 52,
    "height": 70
  },
  {
    "code": "B-2F-2434",
    "x": 1847,
    "y": 2106,
    "width": 52,
    "height": 70
  },
  {
    "code": "B-2F-2441",
    "x": 1420,
    "y": 2106,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2230",
    "x": 3947,
    "y": 1965,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2218",
    "x": 3041,
    "y": 1965,
    "width": 52,
    "height": 70
  },
  {
    "code": "B-2F-2456",
    "x": 781,
    "y": 1965,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2240",
    "x": 3947,
    "y": 1893,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2252",
    "x": 3041,
    "y": 1893,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2253",
    "x": 2936,
    "y": 1893,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2254",
    "x": 2882,
    "y": 1893,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-2F-2255",
    "x": 2829,
    "y": 1893,
    "width": 52,
    "height": 70
  },
  {
    "code": "B-2F-2479",
    "x": 1847,
    "y": 1893,
    "width": 52,
    "height": 70
  },
  {
    "code": "B-2F-2484",
    "x": 1527,
    "y": 1893,
    "width": 52,
    "height": 70
  },
  {
    "code": "B-2F-2486",
    "x": 1420,
    "y": 1893,
    "width": 52,
    "height": 70
  },
  {
    "code": "B-2F-2495",
    "x": 674,
    "y": 1893,
    "width": 52,
    "height": 70
  },
  {
    "code": "B-2F-2903",
    "x": 414,
    "y": 1745,
    "width": 55,
    "height": 66
  },
  {
    "code": "B-2F-2331",
    "x": 1740,
    "y": 2745,
    "width": 51,
    "height": 71
  },
  {
    "code": "B-2F-2344",
    "x": 675,
    "y": 2745,
    "width": 51,
    "height": 71
  },
  {
    "code": "A-2F-2112",
    "x": 4054,
    "y": 2532,
    "width": 51,
    "height": 71
  },
  {
    "code": "A-2F-2114",
    "x": 3948,
    "y": 2532,
    "width": 51,
    "height": 71
  },
  {
    "code": "A-2F-2119",
    "x": 3628,
    "y": 2532,
    "width": 51,
    "height": 71
  },
  {
    "code": "A-2F-2122",
    "x": 3468,
    "y": 2532,
    "width": 51,
    "height": 71
  },
  {
    "code": "A-2F-2126",
    "x": 3095,
    "y": 2532,
    "width": 51,
    "height": 71
  },
  {
    "code": "B-2F-2386",
    "x": 675,
    "y": 2532,
    "width": 51,
    "height": 71
  },
  {
    "code": "B-2F-2401",
    "x": 1421,
    "y": 2319,
    "width": 51,
    "height": 71
  },
  {
    "code": "B-2F-2402",
    "x": 1367,
    "y": 2319,
    "width": 51,
    "height": 71
  },
  {
    "code": "B-2F-2408",
    "x": 728,
    "y": 2319,
    "width": 51,
    "height": 71
  },
  {
    "code": "B-2F-2409",
    "x": 675,
    "y": 2319,
    "width": 51,
    "height": 71
  },
  {
    "code": "A-2F-2176",
    "x": 3735,
    "y": 2178,
    "width": 51,
    "height": 71
  },
  {
    "code": "A-2F-2194",
    "x": 3202,
    "y": 2106,
    "width": 51,
    "height": 71
  },
  {
    "code": "A-2F-2195",
    "x": 3149,
    "y": 2106,
    "width": 51,
    "height": 71
  },
  {
    "code": "A-2F-2202",
    "x": 2723,
    "y": 2106,
    "width": 51,
    "height": 71
  },
  {
    "code": "C-2F-2142",
    "x": 3041,
    "y": 913,
    "width": 53,
    "height": 68
  },
  {
    "code": "B-2F-2384",
    "x": 781,
    "y": 2533,
    "width": 52,
    "height": 69
  },
  {
    "code": "A-2F-2167",
    "x": 2936,
    "y": 2179,
    "width": 52,
    "height": 69
  },
  {
    "code": "A-2F-2228",
    "x": 3788,
    "y": 1966,
    "width": 52,
    "height": 69
  },
  {
    "code": "A-2F-2217",
    "x": 2936,
    "y": 1966,
    "width": 52,
    "height": 69
  },
  {
    "code": "B-2F-2415",
    "x": 876,
    "y": 2178,
    "width": 49,
    "height": 73
  },
  {
    "code": "B-2F-2329",
    "x": 1847,
    "y": 2746,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2330",
    "x": 1793,
    "y": 2746,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2332",
    "x": 1687,
    "y": 2746,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2335",
    "x": 1474,
    "y": 2746,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2337",
    "x": 1367,
    "y": 2746,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2102",
    "x": 3735,
    "y": 2605,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2359",
    "x": 1687,
    "y": 2605,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2113",
    "x": 4001,
    "y": 2533,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2117",
    "x": 3735,
    "y": 2533,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2120",
    "x": 3575,
    "y": 2533,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2124",
    "x": 3202,
    "y": 2533,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2129",
    "x": 2882,
    "y": 2533,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2376",
    "x": 1421,
    "y": 2532,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2400",
    "x": 1474,
    "y": 2320,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2405",
    "x": 928,
    "y": 2320,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2171",
    "x": 3202,
    "y": 2179,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2185",
    "x": 4001,
    "y": 2106,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2189",
    "x": 3735,
    "y": 2106,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2191",
    "x": 3628,
    "y": 2106,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2201",
    "x": 2776,
    "y": 2106,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2435",
    "x": 1794,
    "y": 2106,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2436",
    "x": 1740,
    "y": 2106,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2437",
    "x": 1687,
    "y": 2106,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2438",
    "x": 1633,
    "y": 2106,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2440",
    "x": 1474,
    "y": 2106,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2442",
    "x": 1367,
    "y": 2106,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2227",
    "x": 3734,
    "y": 1965,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2221",
    "x": 3202,
    "y": 1965,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2215",
    "x": 2829,
    "y": 1965,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2214",
    "x": 2776,
    "y": 1965,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2213",
    "x": 2723,
    "y": 1965,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2455",
    "x": 728,
    "y": 1965,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2454",
    "x": 675,
    "y": 1965,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2238",
    "x": 4055,
    "y": 1893,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2239",
    "x": 4001,
    "y": 1893,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2249",
    "x": 3202,
    "y": 1893,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2250",
    "x": 3149,
    "y": 1893,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2256",
    "x": 2776,
    "y": 1893,
    "width": 51,
    "height": 70
  },
  {
    "code": "A-2F-2257",
    "x": 2723,
    "y": 1893,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2480",
    "x": 1794,
    "y": 1893,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2482",
    "x": 1687,
    "y": 1893,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2483",
    "x": 1633,
    "y": 1893,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2485",
    "x": 1474,
    "y": 1893,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2487",
    "x": 1367,
    "y": 1893,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-2F-2494",
    "x": 728,
    "y": 1893,
    "width": 51,
    "height": 70
  },
  {
    "code": "C-2F-2144",
    "x": 2882,
    "y": 913,
    "width": 52,
    "height": 68
  },
  {
    "code": "B-2F-2342",
    "x": 782,
    "y": 2746,
    "width": 51,
    "height": 69
  },
  {
    "code": "B-2F-2343",
    "x": 728,
    "y": 2746,
    "width": 51,
    "height": 69
  },
  {
    "code": "B-2F-2372",
    "x": 1687,
    "y": 2533,
    "width": 51,
    "height": 69
  },
  {
    "code": "B-2F-2373",
    "x": 1633,
    "y": 2533,
    "width": 51,
    "height": 69
  },
  {
    "code": "B-2F-2375",
    "x": 1474,
    "y": 2533,
    "width": 51,
    "height": 69
  },
  {
    "code": "B-2F-2377",
    "x": 1367,
    "y": 2533,
    "width": 51,
    "height": 69
  },
  {
    "code": "B-2F-2385",
    "x": 728,
    "y": 2533,
    "width": 51,
    "height": 69
  },
  {
    "code": "A-2F-2180",
    "x": 4001,
    "y": 2179,
    "width": 51,
    "height": 69
  },
  {
    "code": "B-2F-2424",
    "x": 1687,
    "y": 2179,
    "width": 51,
    "height": 69
  },
  {
    "code": "A-2F-2231",
    "x": 4001,
    "y": 1966,
    "width": 51,
    "height": 69
  },
  {
    "code": "A-2F-2220",
    "x": 3149,
    "y": 1966,
    "width": 51,
    "height": 69
  },
  {
    "code": "B-2F-2902",
    "x": 357,
    "y": 1745,
    "width": 54,
    "height": 65
  },
  {
    "code": "A-2F-2196",
    "x": 3096,
    "y": 2106,
    "width": 50,
    "height": 70
  },
  {
    "code": "A-2F-2243",
    "x": 3735,
    "y": 1893,
    "width": 50,
    "height": 70
  },
  {
    "code": "B-2F-2406",
    "x": 876,
    "y": 2319,
    "width": 49,
    "height": 71
  },
  {
    "code": "C-2F-2145",
    "x": 2829,
    "y": 913,
    "width": 51,
    "height": 68
  },
  {
    "code": "A-2F-2169",
    "x": 3095,
    "y": 2179,
    "width": 51,
    "height": 69
  },
  {
    "code": "B-2F-2914",
    "x": 363,
    "y": 2102.9,
    "width": 48,
    "height": 72.1
  },
  {
    "code": "B-2F-2380",
    "x": 1048,
    "y": 2533,
    "width": 50,
    "height": 69
  },
  {
    "code": "B-2F-2381",
    "x": 995,
    "y": 2533,
    "width": 50,
    "height": 69
  },
  {
    "code": "B-2F-2382",
    "x": 942,
    "y": 2533,
    "width": 50,
    "height": 69
  },
  {
    "code": "A-2F-2166",
    "x": 2883,
    "y": 2179,
    "width": 50,
    "height": 69
  },
  {
    "code": "A-2F-2216",
    "x": 2883,
    "y": 1966,
    "width": 50,
    "height": 69
  },
  {
    "code": "B-2F-2908",
    "x": 345,
    "y": 1941,
    "width": 80,
    "height": 46
  },
  {
    "code": "B-2F-2519",
    "x": 1633,
    "y": 1745,
    "width": 52,
    "height": 66
  },
  {
    "code": "B-2F-2517",
    "x": 1527,
    "y": 1745,
    "width": 52,
    "height": 66
  },
  {
    "code": "B-2F-2503",
    "x": 782,
    "y": 1745,
    "width": 52,
    "height": 66
  },
  {
    "code": "C-2F-2143",
    "x": 2936,
    "y": 914,
    "width": 52,
    "height": 66
  },
  {
    "code": "B-2F-2515",
    "x": 1420,
    "y": 1745,
    "width": 52,
    "height": 66.2
  },
  {
    "code": "B-2F-2507",
    "x": 994,
    "y": 1745,
    "width": 52,
    "height": 66.2
  },
  {
    "code": "C-2F-2146",
    "x": 2776,
    "y": 914,
    "width": 51,
    "height": 67
  },
  {
    "code": "B-2F-2523",
    "x": 1847,
    "y": 1745,
    "width": 51,
    "height": 66
  },
  {
    "code": "B-2F-2522",
    "x": 1794,
    "y": 1745,
    "width": 51,
    "height": 66
  },
  {
    "code": "B-2F-2521",
    "x": 1740,
    "y": 1745,
    "width": 51,
    "height": 66
  },
  {
    "code": "B-2F-2520",
    "x": 1687,
    "y": 1745,
    "width": 51,
    "height": 66
  },
  {
    "code": "B-2F-2516",
    "x": 1474,
    "y": 1745,
    "width": 51,
    "height": 66
  },
  {
    "code": "B-2F-2514",
    "x": 1367,
    "y": 1745,
    "width": 51,
    "height": 66
  },
  {
    "code": "B-2F-2508",
    "x": 1048,
    "y": 1745,
    "width": 51,
    "height": 66
  },
  {
    "code": "B-2F-2506",
    "x": 941,
    "y": 1745,
    "width": 51,
    "height": 66
  },
  {
    "code": "B-2F-2501",
    "x": 675,
    "y": 1745,
    "width": 51,
    "height": 66
  },
  {
    "code": "B-2F-2502",
    "x": 728,
    "y": 1745,
    "width": 51,
    "height": 65
  },
  {
    "code": "C-2F-2147",
    "x": 2723,
    "y": 914,
    "width": 50,
    "height": 66
  },
  {
    "code": "B-2F-2913",
    "x": 413,
    "y": 2104,
    "width": 47,
    "height": 70
  },
  {
    "code": "B-2F-2915",
    "x": 314,
    "y": 2104,
    "width": 47,
    "height": 70
  },
  {
    "code": "B-2F-2510",
    "x": 1151,
    "y": 1745,
    "width": 49,
    "height": 66
  },
  {
    "code": "B-2F-2509",
    "x": 1101,
    "y": 1745,
    "width": 48,
    "height": 65
  },
  {
    "code": "A-2F-2277",
    "x": 3426,
    "y": 1745,
    "width": 40,
    "height": 77
  },
  {
    "code": "B-2F-2340",
    "x": 990,
    "y": 2746,
    "width": 54,
    "height": 49
  }
];

export const HOTSPOTS_2F: FloorHotspotData = {
  floor: '2F',
  imageWidth: W,
  imageHeight: H,
  regions: REGIONS,
  stores: STORES,
  facilities: [],
};
