// AUTO-GENERATED by scripts/buildAllHotspots.mjs
// 7F SVG 파싱 + PNG OCR 매칭 결과
// 총 0개 셀 매칭 (디렉터리 7F: 3개)

import { FloorHotspotData } from '@/components/map/ImageOverlayMap';

const W = 4406;
const H = 3077;

const REGIONS: FloorHotspotData['regions'] = [
  {
    "building": "A",
    "polygon": [
      [
        2334.88,
        2157.88
      ],
      [
        2497,
        2157.88
      ],
      [
        2497,
        2320
      ],
      [
        2334.88,
        2320
      ]
    ]
  }
] as FloorHotspotData['regions'];

const STORES: FloorHotspotData['stores'] = [];

export const HOTSPOTS_7F: FloorHotspotData = {
  floor: '7F',
  imageWidth: W,
  imageHeight: H,
  regions: REGIONS,
  stores: STORES,
  facilities: [],
};
