// AUTO-GENERATED by scripts/buildAllHotspots.mjs
// B1F SVG 파싱 + PNG OCR 매칭 결과
// 총 34개 셀 매칭 (디렉터리 B1F: 732개)

import { FloorHotspotData } from '@/components/map/ImageOverlayMap';

const W = 4612;
const H = 3190;

const REGIONS: FloorHotspotData['regions'] = [
  {
    "building": "A",
    "polygon": [
      [
        2428.8,
        1883
      ],
      [
        4346.1,
        1883
      ],
      [
        4346.1,
        3153
      ],
      [
        2428.8,
        3153
      ]
    ]
  },
  {
    "building": "B",
    "polygon": [
      [
        380.7,
        1883
      ],
      [
        2259,
        1883
      ],
      [
        2259,
        3159
      ],
      [
        380.7,
        3159
      ]
    ]
  },
  {
    "building": "C",
    "polygon": [
      [
        2354.8,
        1247
      ],
      [
        4340,
        1247
      ],
      [
        4340,
        1876.9
      ],
      [
        2354.8,
        1876.9
      ]
    ]
  },
  {
    "building": "N",
    "polygon": [
      [
        2546,
        30
      ],
      [
        4346,
        30
      ],
      [
        4346,
        856
      ],
      [
        2546,
        856
      ]
    ]
  }
] as FloorHotspotData['regions'];

const STORES = [
  {
    "code": "B-B1F-257",
    "x": 1234.8,
    "y": 1883,
    "width": 50.2,
    "height": 71
  },
  {
    "code": "B-B1F-256",
    "x": 1286.8,
    "y": 1883,
    "width": 51.2,
    "height": 71
  },
  {
    "code": "B-B1F-255",
    "x": 1339.8,
    "y": 1883,
    "width": 51.2,
    "height": 71
  },
  {
    "code": "B-B1F-254",
    "x": 1392.8,
    "y": 1883,
    "width": 51.2,
    "height": 71
  },
  {
    "code": "B-B1F-253",
    "x": 1445.8,
    "y": 1883,
    "width": 52.2,
    "height": 71
  },
  {
    "code": "B-B1F-251",
    "x": 1552.8,
    "y": 1883.5,
    "width": 52.2,
    "height": 70.5
  },
  {
    "code": "B-B1F-246",
    "x": 1872.8,
    "y": 1883,
    "width": 51.2,
    "height": 71
  },
  {
    "code": "B-B1F-241",
    "x": 2139.8,
    "y": 1883,
    "width": 62.2,
    "height": 71
  },
  {
    "code": "B-B1F-240",
    "x": 2203.8,
    "y": 1883,
    "width": 55.2,
    "height": 71
  },
  {
    "code": "B-B1F-222",
    "x": 1234.8,
    "y": 2019,
    "width": 50.2,
    "height": 73
  },
  {
    "code": "B-B1F-223",
    "x": 1286.8,
    "y": 2019,
    "width": 51.2,
    "height": 73
  },
  {
    "code": "B-B1F-225",
    "x": 1392.8,
    "y": 2019,
    "width": 51.2,
    "height": 73
  },
  {
    "code": "B-B1F-226",
    "x": 1445.8,
    "y": 2019,
    "width": 52.2,
    "height": 73
  },
  {
    "code": "B-B1F-228",
    "x": 1552.8,
    "y": 2019,
    "width": 52.2,
    "height": 73
  },
  {
    "code": "B-B1F-233",
    "x": 1872.8,
    "y": 2019,
    "width": 51.2,
    "height": 73
  },
  {
    "code": "B-B1F-239",
    "x": 2203.8,
    "y": 2019,
    "width": 55.2,
    "height": 73
  },
  {
    "code": "B-B1F-263",
    "x": 2157.4,
    "y": 2435.1,
    "width": 101.6,
    "height": 84
  },
  {
    "code": "C-B1F-735",
    "x": 4246,
    "y": 1636,
    "width": 91,
    "height": 143
  },
  {
    "code": "A-B1F-147",
    "x": 2428.8,
    "y": 1883,
    "width": 51.2,
    "height": 71
  },
  {
    "code": "A-B1F-150",
    "x": 2588.8,
    "y": 1883,
    "width": 51.2,
    "height": 71
  },
  {
    "code": "A-B1F-151",
    "x": 2641.8,
    "y": 1883.4,
    "width": 56.2,
    "height": 70.5
  },
  {
    "code": "A-B1F-154",
    "x": 2854.8,
    "y": 1883,
    "width": 51.2,
    "height": 71
  },
  {
    "code": "A-B1F-157",
    "x": 3014.8,
    "y": 1883,
    "width": 51.2,
    "height": 71
  },
  {
    "code": "A-B1F-158",
    "x": 3067.8,
    "y": 1883,
    "width": 51.2,
    "height": 71
  },
  {
    "code": "A-B1F-161",
    "x": 3227.8,
    "y": 1883,
    "width": 51.2,
    "height": 71
  },
  {
    "code": "A-B1F-162",
    "x": 3280.8,
    "y": 1883.5,
    "width": 65.2,
    "height": 70.5
  },
  {
    "code": "A-B1F-144",
    "x": 2428.8,
    "y": 2019,
    "width": 51.2,
    "height": 73
  },
  {
    "code": "A-B1F-140",
    "x": 2641.8,
    "y": 2019.5,
    "width": 56.2,
    "height": 72.5
  },
  {
    "code": "A-B1F-137",
    "x": 2854.8,
    "y": 2019,
    "width": 51.2,
    "height": 73
  },
  {
    "code": "A-B1F-133",
    "x": 3067.8,
    "y": 2019,
    "width": 51.2,
    "height": 73
  },
  {
    "code": "A-B1F-129",
    "x": 3280.8,
    "y": 2019.5,
    "width": 65.2,
    "height": 72.5
  },
  {
    "code": "A-B1F-128",
    "x": 3581.8,
    "y": 2019,
    "width": 70.2,
    "height": 73
  },
  {
    "code": "A-B1F-127",
    "x": 3653.8,
    "y": 2019,
    "width": 51.2,
    "height": 73
  },
  {
    "code": "A-B1F-119",
    "x": 4079.8,
    "y": 2019,
    "width": 66.2,
    "height": 73
  }
];

export const HOTSPOTS_B1F: FloorHotspotData = {
  floor: 'B1F',
  imageWidth: W,
  imageHeight: H,
  regions: REGIONS,
  stores: STORES,
  facilities: [],
};
