// AUTO-GENERATED by scripts/buildAllHotspots.mjs
// 8F SVG 파싱 + PNG OCR 매칭 결과
// 총 0개 셀 매칭 (디렉터리 8F: 2개)

import { FloorHotspotData } from '@/components/map/ImageOverlayMap';

const W = 4406;
const H = 3077;

const REGIONS: FloorHotspotData['regions'] = [
  {
    "building": "N",
    "polygon": [
      [
        3832,
        114
      ],
      [
        4259,
        114
      ],
      [
        4259,
        677
      ],
      [
        3832,
        677
      ]
    ]
  }
] as FloorHotspotData['regions'];

const STORES: FloorHotspotData['stores'] = [];

export const HOTSPOTS_8F: FloorHotspotData = {
  floor: '8F',
  imageWidth: W,
  imageHeight: H,
  regions: REGIONS,
  stores: STORES,
  facilities: [],
};
