// AUTO-GENERATED by scripts/buildAllHotspots.mjs
// 1F SVG 파싱 + PNG OCR 매칭 결과
// 총 63개 셀 매칭 (디렉터리 1F: 714개)

import { FloorHotspotData } from '@/components/map/ImageOverlayMap';

const W = 4406;
const H = 3077;

const REGIONS: FloorHotspotData['regions'] = [
  {
    "building": "A",
    "polygon": [
      [
        2409,
        1784
      ],
      [
        4329,
        1784
      ],
      [
        4329,
        3183
      ],
      [
        2409,
        3183
      ]
    ]
  },
  {
    "building": "B",
    "polygon": [
      [
        111.88,
        1784
      ],
      [
        2114,
        1784
      ],
      [
        2114,
        3183
      ],
      [
        111.88,
        3183
      ]
    ]
  },
  {
    "building": "C",
    "polygon": [
      [
        2409,
        849
      ],
      [
        4329,
        849
      ],
      [
        4329,
        2092
      ],
      [
        2409,
        2092
      ]
    ]
  },
  {
    "building": "N",
    "polygon": [
      [
        2529,
        119
      ],
      [
        3694,
        119
      ],
      [
        3694,
        699
      ],
      [
        2529,
        699
      ]
    ]
  }
] as FloorHotspotData['regions'];

const STORES = [
  {
    "code": "B-1F-1561",
    "x": 1695,
    "y": 1784,
    "width": 104,
    "height": 132
  },
  {
    "code": "B-1F-1537",
    "x": 262,
    "y": 1784,
    "width": 75,
    "height": 132
  },
  {
    "code": "B-1F-1439",
    "x": 248,
    "y": 2027,
    "width": 166,
    "height": 52
  },
  {
    "code": "B-1F-1322",
    "x": 928,
    "y": 2868,
    "width": 123,
    "height": 63
  },
  {
    "code": "A-1F-1141",
    "x": 4009,
    "y": 2423,
    "width": 80,
    "height": 83
  },
  {
    "code": "A-1F-1142",
    "x": 3547,
    "y": 2933,
    "width": 139,
    "height": 47
  },
  {
    "code": "C-1F-1127",
    "x": 4024,
    "y": 1396,
    "width": 106,
    "height": 59
  },
  {
    "code": "C-1F-1132",
    "x": 3461,
    "y": 1396,
    "width": 106,
    "height": 59
  },
  {
    "code": "C-1F-1114",
    "x": 4024,
    "y": 1205,
    "width": 106,
    "height": 59
  },
  {
    "code": "C-1F-1119",
    "x": 3461,
    "y": 1205,
    "width": 106,
    "height": 59
  },
  {
    "code": "C-1F-1131",
    "x": 3568.88,
    "y": 1395.88,
    "width": 106.12,
    "height": 59.12
  },
  {
    "code": "C-1F-1115",
    "x": 3915.88,
    "y": 1204.88,
    "width": 106.12,
    "height": 59.12
  },
  {
    "code": "C-1F-1118",
    "x": 3568.88,
    "y": 1204.88,
    "width": 106.12,
    "height": 59.12
  },
  {
    "code": "B-1F-1323",
    "x": 1253,
    "y": 2934,
    "width": 120,
    "height": 52
  },
  {
    "code": "C-1F-1128",
    "x": 3917,
    "y": 1396,
    "width": 105,
    "height": 59
  },
  {
    "code": "C-1F-1157",
    "x": 4055,
    "y": 1784,
    "width": 75,
    "height": 82
  },
  {
    "code": "B-1F-1416",
    "x": 553,
    "y": 2423,
    "width": 73,
    "height": 82
  },
  {
    "code": "C-1F-1156",
    "x": 3903,
    "y": 1784,
    "width": 73,
    "height": 82
  },
  {
    "code": "C-1F-1141",
    "x": 4029,
    "y": 1590,
    "width": 101,
    "height": 59
  },
  {
    "code": "C-1F-1143",
    "x": 3825,
    "y": 1590,
    "width": 101,
    "height": 59
  },
  {
    "code": "C-1F-1161",
    "x": 3682,
    "y": 1784,
    "width": 72,
    "height": 82
  },
  {
    "code": "C-1F-1163",
    "x": 3535,
    "y": 1784,
    "width": 72,
    "height": 82
  },
  {
    "code": "C-1F-1142",
    "x": 3928,
    "y": 1590,
    "width": 99,
    "height": 59
  },
  {
    "code": "C-1F-1162",
    "x": 3609,
    "y": 1784,
    "width": 71,
    "height": 82
  },
  {
    "code": "A-1F-1185",
    "x": 3192,
    "y": 2222,
    "width": 83,
    "height": 70
  },
  {
    "code": "C-1F-1145",
    "x": 3559,
    "y": 1590,
    "width": 97,
    "height": 59
  },
  {
    "code": "C-1F-1146",
    "x": 3461,
    "y": 1590,
    "width": 96,
    "height": 59
  },
  {
    "code": "A-1F-1152",
    "x": 3209,
    "y": 2423,
    "width": 66,
    "height": 83
  },
  {
    "code": "B-1F-1327",
    "x": 1694,
    "y": 2934,
    "width": 105,
    "height": 52
  },
  {
    "code": "B-1F-1326",
    "x": 1587,
    "y": 2934,
    "width": 105,
    "height": 52
  },
  {
    "code": "B-1F-1325",
    "x": 1481,
    "y": 2934,
    "width": 105,
    "height": 52
  },
  {
    "code": "B-1F-1324",
    "x": 1374,
    "y": 2934,
    "width": 105,
    "height": 52
  },
  {
    "code": "A-1F-1127",
    "x": 3209,
    "y": 2508,
    "width": 66,
    "height": 81
  },
  {
    "code": "B-1F-1407",
    "x": 1254,
    "y": 2423,
    "width": 65,
    "height": 82
  },
  {
    "code": "C-1F-1116",
    "x": 3825,
    "y": 1204.88,
    "width": 90.11,
    "height": 59.12
  },
  {
    "code": "C-1F-1129",
    "x": 3825,
    "y": 1396,
    "width": 89,
    "height": 59
  },
  {
    "code": "B-1F-1408",
    "x": 1054,
    "y": 2423,
    "width": 62,
    "height": 82
  },
  {
    "code": "A-1F-1151",
    "x": 3350,
    "y": 2423,
    "width": 70,
    "height": 83
  },
  {
    "code": "B-1F-1452",
    "x": 554,
    "y": 2222,
    "width": 72,
    "height": 70
  },
  {
    "code": "B-1F-1432",
    "x": 2043,
    "y": 2222,
    "width": 71,
    "height": 70
  },
  {
    "code": "A-1F-1187",
    "x": 3049,
    "y": 2222,
    "width": 70,
    "height": 70
  },
  {
    "code": "A-1F-1186",
    "x": 3121,
    "y": 2222,
    "width": 69,
    "height": 70
  },
  {
    "code": "B-1F-1433",
    "x": 1973,
    "y": 2222,
    "width": 67,
    "height": 70
  },
  {
    "code": "A-1F-1174",
    "x": 4062,
    "y": 2222,
    "width": 66,
    "height": 70
  },
  {
    "code": "A-1F-1194",
    "x": 2477,
    "y": 2222,
    "width": 66,
    "height": 70
  },
  {
    "code": "A-1F-1195",
    "x": 2409,
    "y": 2222,
    "width": 66,
    "height": 70
  },
  {
    "code": "C-1F-1130",
    "x": 3677,
    "y": 1396,
    "width": 77,
    "height": 59
  },
  {
    "code": "C-1F-1117",
    "x": 3677,
    "y": 1205,
    "width": 77,
    "height": 59
  },
  {
    "code": "B-1F-1437",
    "x": 553,
    "y": 2027,
    "width": 87,
    "height": 52
  },
  {
    "code": "B-1F-1414",
    "x": 681,
    "y": 2423,
    "width": 52,
    "height": 82
  },
  {
    "code": "B-1F-1413",
    "x": 735,
    "y": 2423,
    "width": 51,
    "height": 82
  },
  {
    "code": "B-1F-1415",
    "x": 628,
    "y": 2423,
    "width": 51,
    "height": 82
  },
  {
    "code": "B-1F-1330",
    "x": 2042,
    "y": 2934,
    "width": 72,
    "height": 52
  },
  {
    "code": "B-1F-1448",
    "x": 788,
    "y": 2222,
    "width": 52,
    "height": 70
  },
  {
    "code": "B-1F-1451",
    "x": 628,
    "y": 2222,
    "width": 52,
    "height": 70
  },
  {
    "code": "A-1F-1190",
    "x": 2890,
    "y": 2222,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-1F-1446",
    "x": 895,
    "y": 2222,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-1F-1447",
    "x": 842,
    "y": 2222,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-1F-1449",
    "x": 735,
    "y": 2222,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-1F-1450",
    "x": 682,
    "y": 2222,
    "width": 51,
    "height": 70
  },
  {
    "code": "B-1F-1438",
    "x": 1588,
    "y": 2222,
    "width": 51,
    "height": 69
  },
  {
    "code": "B-1F-1441",
    "x": 1428,
    "y": 2222,
    "width": 51,
    "height": 69
  },
  {
    "code": "B-1F-1470",
    "x": 1973,
    "y": 2027,
    "width": 67,
    "height": 52
  }
];

export const HOTSPOTS_1F: FloorHotspotData = {
  floor: '1F',
  imageWidth: W,
  imageHeight: H,
  regions: REGIONS,
  stores: STORES,
  facilities: [],
};
