// OCR 결과를 디렉터리와 매칭해서 최종 hotspots_2F.ts 생성.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');

const OCR_JSON = path.join(__dirname, 'out/ocr_2F.json');
const DIR_JSON = path.join(ROOT, 'src/data/stores/directory.json');
const OUT_TS = path.join(ROOT, 'src/data/floors/hotspots_2F.ts');

const { viewBox, cells } = JSON.parse(fs.readFileSync(OCR_JSON, 'utf8'));
const directory = JSON.parse(fs.readFileSync(DIR_JSON, 'utf8'));

const dir2F = directory.filter((s) => s.floor === '2F' && s.building && s.code);
const byBuilding = { A: [], B: [], C: [], N: [] };
for (const s of dir2F) {
  if (byBuilding[s.building]) byBuilding[s.building].push(s);
}
console.log(
  'Directory 2F:',
  Object.fromEntries(Object.entries(byBuilding).map(([k, v]) => [k, v.length])),
);

// ── 매칭 함수 ────────────────────────────────────────────────
function matchByOcr(cell) {
  const list = byBuilding[cell.building] ?? [];
  const ocr = cell.ocr || '';
  if (!ocr) return null;

  // 완전 일치 우선
  let exact = list.filter((s) => s.unit === ocr);
  if (exact.length === 1) return { store: exact[0], mode: 'exact' };

  // endsWith 매칭 (예: OCR '342' → unit '2342')
  // 3자리 이상만 허용 — 2자리 이하는 모호해서 false positive 위험
  if (/^\d{3,4}$/.test(ocr)) {
    let ends = list.filter((s) => s.unit && String(s.unit).endsWith(ocr));
    if (ends.length === 1) return { store: ends[0], mode: 'endsWith' };
    // 여러 개 후보면 unit의 총 길이가 짧은 것 우선
    if (ends.length > 1) {
      ends.sort((a, b) => String(a.unit).length - String(b.unit).length);
      return { store: ends[0], mode: 'endsWith-multi' };
    }
  }
  return null;
}

// ── 각 셀에 매칭 시도 ────────────────────────────────────────
const assigned = new Set(); // 중복 방지
const matched = [];
const unmatched = [];
const modeStats = {};

for (const c of cells) {
  const r = matchByOcr(c);
  if (r && !assigned.has(r.store.code)) {
    assigned.add(r.store.code);
    matched.push({ ...c, code: r.store.code, name: r.store.name, mode: r.mode });
    modeStats[r.mode] = (modeStats[r.mode] || 0) + 1;
  } else {
    unmatched.push(c);
  }
}

console.log('\n매칭 결과:');
console.log('  성공:', matched.length);
console.log('  실패:', unmatched.length);
console.log('  모드별:', modeStats);

// spatial fallback 비활성화 — OCR 매칭 실패한 셀은 점포 없음으로 간주 (false positive 방지)
// 화장실·엘베·벽 같은 non-store 영역에 엉뚱한 점포가 배정되는 문제 해결
const allMapped = matched;
console.log('\nOCR 매칭만 사용 (spatial fallback 비활성)');
console.log('\n최종 배정:', allMapped.length, '/ 디렉터리 2F:', dir2F.length);

// ── TypeScript 파일 생성 ────────────────────────────────────
const cellsTs = allMapped.map((c) => ({
  code: c.code,
  x: Math.round(c.x * 100) / 100,
  y: Math.round(c.y * 100) / 100,
  width: Math.round(c.w * 100) / 100,
  height: Math.round(c.h * 100) / 100,
}));

const header = `// AUTO-GENERATED by scripts/matchStores.mjs — edit 시 pipeline 재실행 필요
// 2F SVG 파싱 + PNG OCR 매칭 결과
// 총 ${allMapped.length}개 셀 매칭 (디렉터리 2F: ${dir2F.length}개)

import { FloorHotspotData } from '@/components/map/ImageOverlayMap';

const W = ${viewBox.w};
const H = ${viewBox.h};

const STORES = ${JSON.stringify(cellsTs, null, 2)};

export const HOTSPOTS_2F: FloorHotspotData = {
  floor: '2F',
  imageWidth: W,
  imageHeight: H,
  regions: [
    { building: 'B', polygon: [[140, 1250], [2080, 1250], [2080, 2980], [140, 2980]] },
    { building: 'A', polygon: [[2230, 1780], [4330, 1780], [4330, 3000], [2230, 3000]] },
    { building: 'C', polygon: [[2230, 770], [4330, 770], [4330, 1750], [2230, 1750]] },
    { building: 'N', polygon: [[2230, 50], [4350, 50], [4350, 730], [2230, 730]] },
  ],
  stores: STORES,
  facilities: [],
};
`;

fs.writeFileSync(OUT_TS, header);
console.log('→ saved:', OUT_TS);
